Mykindos/BetterPvP

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/SmokeArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/PrepareArrowSkill.java
- champions/src/main/resources/config.yml
Changes:
- Added 1:1 replica of Smoke Arrow skill from Mineplex. 
- Add PrepareArrowSkill#onFire to allow skills to listen for when the shooter shoots the arrow projectile.
> Create Smoke Arrow skill

- clans/src/main/java/me/mykindos/betterpvp/clans/Clans.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/events/TerritoryInteractEvent.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/commands/commands/ClansCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/Fields.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/FieldsListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/block/GoldChunkOre.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/block/LootChest.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/block/SimpleOre.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/commands/FieldsCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/commands/subcommands/FieldsClaimSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/commands/subcommands/FieldsInfoSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/commands/subcommands/FieldsRespawnSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/CustomOre.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/FieldsBlock.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/FieldsInteractable.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/FieldsOre.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/repository/FieldsBlockEntry.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/repository/FieldsRepository.java
- clans/src/main/java/me/mykindos/betterpvp/clans/utilities/ClansNamespacedKeys.java
- clans/src/main/resources/clans-migrations/V1_2__fields.sql
- clans/src/main/resources/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/client/commands/ClientCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/client/events/ClientAdministrateEvent.java
Changes:
- Implementation Fields clans zone 
- Create `TerritoryInteractEvent` to listen for whenever a user interacts with a claimed territory, whether it be placing, breaking or clicking blocks.
- Fix colored messaging when walking to Fields territory.
- Create `ClientAdministrateEvent` to listen for whenever an admin uses the `/client admin` command
- Creat `/fields` command and subcommand
Behavior:
- Fields:
- Configurable values for all interactables.
- Condition-based respawn delay modifiers, configurable per player-count. 
- `FieldsInteractable` represents all interactable blocks within fields, which include ores and clickable blocks. A default implementation of this is `LootChest`
- `SimpleOre` is an interactable that represents all default minecraft ores that drop a single …
> Create Fields & new utility events and classes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/Clan.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/events/EnergyCheckEvent.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEnergyListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanPropertyListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilTime.java
Add a title/chat warning for low energy, which is checked every 5 minutes. If your clan has less than `1.0` hours, receive a warning through title and chat.
Also fixes a bug in UtilTime.getTIme chain.
> Add a warning for low energy.

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/SkillMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ComboAttack.java
- champions/src/main/resources/config.yml
- made it so the book amount is the same as the skill level for easier skill building
- replaced the emerald on the top right with a gold ingot cuz it looks nicer and is the same as mineplex
- renamed repeated strikes to combo attack because mineplex had the same ability with a different name (less confusing for returning players)
[skill menu](https://ibb.co/DGKmryp)
> skill menu

- clans/src/main/java/me/mykindos/betterpvp/clans/Clans.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/ProgressionAdapter.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/Adapters.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/Compatibility.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/PluginAdapter.java
Changes:
- Create `@PluginAdapter` annotation. Classes annotated with this annotation can be reflectively obtained by a module, then passed into an `Adapters` class instance to force the creation of a new instance of that class using the injector provided by that module.
- Create `Compatibility` class with convenience fields for convenience. Currently only supports `MYTHIC_MOBS` and `ITEMS_ADDER` boolean fields to know if either of those plugins are enabled.
- Adjust `ProgressionAdapter` in the clans module to work with the new adapter-style system.
> Create plugin adapter annotation to support plugin-dependent classes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClaimSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/UnclaimSubCommand.java
Implements #71. Admins in /client admin can claim more territory than a Clan is normally allowed to have (for handling accidental/mistaken/bugged disbands) according to their members. Territory cannot be unclaimed if the Clan that holds it has an admin in /client admin in it (to prevent unclaiming territory that would otherwise be unclaimable while in the process of restoring a Clans claims).
> Admin claim/unclaim QOL

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/Clan.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ListSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/SetEnergySubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/StuckSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/delayedactions/events/ClanStuckTeleportEvent.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilWorld.java
1. Implements https://github.com/Mykindos/BetterPvP/issues/66. Adds setEnergy in clan.java and a new admin command /c setenergy.
2. Implements #70. Adds /c list which lists all clans in the server.
3. Implements #73. Adds /c stuck which teleports the user after a lengthy delay out of a claimed area.
> Added the following c subcommands: setenergy, list, stuck

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/RopedArrow.java
- champions/src/main/resources/config.yml
Changes:
- Allow players to cycle between pull strengths on Roped Arrow by left clicking their bow once prepared.
- Add an [indicator](https://i.imgur.com/itRY92M.png) above players' hotbars displaying the pull strength.
- For each level of pull strength, your cooldown is doubled, with a base value of 4 seconds. The max pull strength matches the current velocity strength, and the cooldown is on par to what it was before.
> Add pull strengths to roped arrow

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansExplosionListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/FieldsListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/event/FieldsInteractableUseEvent.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/FieldsBlock.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/ProgressionAdapter.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/listener/MiningListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/CoreNamespaceKeys.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/blocktag/BlockTaggingListener.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/Leaderboard.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/repository/StatsRepository.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/data/CustomDataType.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/data/PersistentUUIDType.java
- progression/src/main/java/me/mykindos/betterpvp/progression/listener/ProgressionListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/model/stats/ProgressionStatsRepository.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/data/FishingWeightLeaderboard.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/listener/FishingListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/listener/FishingStatsListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/repository/FishingRepository.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/mining/Mining.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/mining/MiningService.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/mining/data/MiningData.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/mining/data/MiningOresMinedLeaderboard.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/mining/listener/MiningStatsListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/mining/repository/MiningRepository.java
- progression/src/main/resources/config.yml
- progression/src/main/resources/progression-migrations/V1_1__progression.sql
Changes:
- Add mining progression tree
- Configurable XP per material type
- Add `Total Ores Mined` leaderboard.
- Configurable minimum XP threshold to only count certain blocks towards statistics.
> Complete mining progression tree

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/OtherClanCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/ClanMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/AlliesButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/ClanCommandButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/ClanUpgradesButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/ClanVaultButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/EnemiesButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/EnergyButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/LeaveClanButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/TerritoryButton.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/ItemView.java
Changes:
- Create ItemStack builder class `ItemView`
- Items with custom model data attempt to check if `ItemsAdder` plugin is on (resourcepack provider) and, in the case that it isn't enabled it uses the fallback item material.
> Item Builder

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- Bat squeaks will now play when you try to use an ability while silenced
> added silence bat squeaks from mineplex

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/DeleteBuildButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/EditBuildButton.java
Fixes #174. Because of how getButton is implemented, it finds the first item in the menu that matches the interacted with item. Items match if they share the same meta-data, which all the edit/delete build buttons did. Therefore, it would always select the first one it came across. By renaming them, this prevents this issue from happening.
> Fix only being able to edit/delete the first build.

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/event/LoadBuildsEvent.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/listeners/BuildListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
Changes:
- Fix memory leak caused by players leaving and `RoleListener` not removing them from the `RoleManager`
- Create `LoadBuildsEvent` called after `GamerBuilds` are loaded asynchronously upon a player logging in.
- Properly track players on active skills after their builds are loaded and not as soon as they join.
Aims to fix #134 for all skills, not just Flash. Should also make it so equip messages are displayed upon logging in for all players who have an equipped set.
> Fix skills not properly tracking players upon relogging

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Backstab.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ComboAttack.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SilencingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ViperStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Concussion.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/CripplingBlow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/PowerChop.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Cleave.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/MoltenBlast.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/axe/WolvesFury.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Overcharge.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Volley.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/Entangle.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/Longshot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/PrepareArrowSkill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/combat/damage/DamageListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansDeathListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/damagelog/DamageLog.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/death/DeathListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/death/events/CustomDeathEvent.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/events/CustomDamageEvent.java
Changes:
- Replace reasons in `CustomDeathEvent` with components.
- Allow for modules to replace the name formatting for the death event.
- Reasons are concatenated with a comma. Example:
Aims to implement #139
> Allow for reason stacking in death messages

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/leaderboard/ClanLeaderboard.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/ProgressionAdapter.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/listener/MiningListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/perks/BaseFishingPerk.java
- core/src/main/java/me/mykindos/betterpvp/core/client/listener/ClientListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/Adapters.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/PluginAdapter.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/PluginAdapters.java
- core/src/main/java/me/mykindos/betterpvp/core/gamer/Gamer.java
- core/src/main/java/me/mykindos/betterpvp/core/gamer/listeners/GamerListener.java
- core/src/main/java/me/mykindos/betterpvp/core/listener/loader/ListenerLoader.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/display/PlayerList.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/display/PlayerListType.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/event/PlayerCaughtFishEvent.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/event/PlayerStartFishingEvent.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/listener/FishingListener.java
Changes:
- Add a custom header and footer attachable object `PlayerList` on gamers.
- Fix admin clans being removed from the cache by `ClanLeaderboard`
- Add a way to ignore fish weight on catch to avoid getting blocked by the rod requirement 
- Fix Clans <-> Progression co-dependency
> Multi-plugin adapters, custom tab header/footer impl, fixes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/BuildManager.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/listeners/BuildListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/repository/BuildRepository.java
- champions/src/main/java/me/mykindos/betterpvp/champions/commands/ChampionsCommand.java
#253, #210. On champions reload, disabled skills are now removed from builds and points refunded. Default builds now use the same method as saved builds, and won't take points from disabled/null skills. A new notification is given to players if a skill they had is no longer available.
This does not update builds in the database, if a player does not change their build in the build table, it will continue to give the warning.
> Update build loading.

- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java
Changes:
- Claim outlines are now packet-based, meaning re-logging or clicking the blocks will reset their state.
Fixes #230
> Make packet-based claim outlines

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
Changes:
- Make ToggleSkill work on all SkillTypes. This means that we must be careful implementing ToggleSkill on abilities within the same class to avoid having multiple skills to trigger at once. Restrict them to a singular type.
Changes were tested.
Fixes #245
> Allow ToggleSkill to work on all SkillTypes

- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/Gamer.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/click/RightClickListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
Changes:
- Migrate to state-based checking for sword and shield right clicking.
- Remove extra tick extension on all right-clicks for every other item.
Changes were tested.
> Remove extra tick extension on blocking

- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
- core/src/main/java/me/mykindos/betterpvp/core/redis/Redis.java
- core/src/main/java/me/mykindos/betterpvp/core/redis/RedisCredentials.java
- core/src/main/resources/config.yml
Changes:
- Add `enabled` boolean option in Core `config.yml` under the `redis` subsection.
- `password` field in the `redis` subsection located in the Core `config.yml` is no longer required.
- Added logging for Redis enable/disable.
Changes were tested.
> Remove hard redis requirement to host a BetterPvP server

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/listeners/WeaponListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/types/ChannelWeapon.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/types/InteractWeapon.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/legendaries/KnightsGreatlance.java
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- core/src/main/java/me/mykindos/betterpvp/core/Core.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientObserver.java
- core/src/main/java/me/mykindos/betterpvp/core/redis/Redis.java
Changes: 
- Remove [improper asynchronous task shutdown warning](https://cdn.discordapp.com/attachments/695630666775265360/1191317275739951144/image.png?ex=65a4ffac&is=65928aac&hm=deb3121301337eb39f60fdd77873b0df6db0a9bc1f228c71d172c4acb2c066d1&) (@Mykindos) ([Log example](https://mcpaste.io/e185855e2b4ef7a8))
- Fix SQL statement errors introduced in #256 
- Restrict click registration checks to only `ChannelWeapon`s, which are mostly only the legendaries. All other weapons use default fallback behavior using `PlayerInteractEvent`
Changes were all tested.
> QoL fixes for click registration and warning removal

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/HeavyArrows.java
- champions/src/main/resources/configs/skills/skills.yml
- fixed config value name being wrong
- nerfed energy slightly because of new energy regen rate
> Heavy Arrows Energy Fixes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/data/ChargeData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/FleshHook.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/LightningOrb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/GlacialPrison.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/StaticLazer.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/ThrowingWeb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/legendaries/KnightsGreatlance.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/ThrowableHandler.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/ThrowableItem.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/listeners/ThrowableListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
Changes:
- Improve throwable item detection using interpolation if nearby checks fail.
- Fix issue were Flesh Hook would have a 250 millisecond delay before firing.
- [Make Flesh Hook work like in Mineplex](https://youtu.be/tqHpIMMT5F0)
Fixes #292 
Fixes #231 
> Improve throwable item detection and make Mineplex 1:1 FleshHook replica

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/resources/configs/skills/skills.yml
scales cooldown instead of max charges so that levels below 5 arent useless
> flash slight rebalance

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/axe/Agility.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/axe/WolvesFury.java
Fixes #334
Fixes #335
Fixes #336
Changes wolf fury to use getDuration for duration.
Actually implements agility, which now reduces all damage, but is cancelled on any interaction by user. Agility now correctly ends after its duration.
> Update Agility and Wolfs Fury

- clans/src/main/java/me/mykindos/betterpvp/clans/utilities/ClansNamespacedKeys.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/listener/CannonListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/model/Cannon.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/model/CannonManager.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- Fix cannons loading improperly after a server crash.
- Separate instruction and healthbar text displays on cannons.
- Cannon healthbar moved right ontop of cannons and lowered its text opacity.
- Text displays on cannons are now placed on the `text_legend` and `text_healthbar` location of the model bone.
- Create utility methods to set/get view range of Display entities in block units
> Fix force-shutdown cannon unload bug

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
Fixes #474 - 
Move an addition by Rey to after door cancel logic is handled, so that the cooldown is applied.
> Fix skills being activated by iron doors/trapdoors

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/BreakFall.java
Break fall now cancels the event if the damage taken was below its reduction threshold
did this on mineplex
> break fall fix

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/data/ChargeData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/GiantsBroadsword.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/HyperAxe.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/BlackHole.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/Scythe.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/ScytheListener.java
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- champions/src/main/resources/configs/weapons/legendaries.yml
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
- Add `Scythe of the Fallen Lord`
- Life steal on hit
- Black hole skill shot
- Make `Hyper Axe` do 5 damage instead of 4
- Make `Giant's Broadsword` do 9 damage instead of 10
> Scythe of the Fallen Lord, Giant's Broadsword nerf, Hyper Axe buff

- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/listener/CannonListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/EntityRemovalReason.java
- Fix cannons throwing errors in unloaded chunks. 
- This is done by checking the removal reason of the entity to see if the entity was destroyed on removal (death or plugin removal) or not (chunk unloading, dimension changes, player unloading)
> Fix cannons throwing errors in unloaded chunks

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Evade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/ExcessiveForce.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/BullsCharge.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/HoldPosition.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/Riposte.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/Disengage.java
- Bulls charge end message playing 1 second after it actually expired
- Bulls charge particles being wrong
- Added end message to all skills that didn't have them(excessive force, hold position)
- Fixed fail messages for evade and disengage
- Fixed excessive force updateEvent running on the wrong frequency
> many fixes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/LightningOrb.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/ThrowableHandler.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/ThrowableListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/listeners/ThrowableItemListener.java
Add sounds on throw and travel from ice prison and lightning orb
Change ice prison to decay from top to bottom instead of all at once. The speed is now controlled by the variance variable
Fixes #612
> Update ice prison (and lightning orb sound)

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/FireBlast.java
Added event handler onEntityDamageByEntity to prevent Fireblast from being deflected by players/entities.
#707 
- [✓] I have performed a self-review of my code
- [✓] I have tested my changes.
> fixed issue of Molten/Fire blast being deflected

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/FreezeCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/UnfreezeCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/EffectTypes.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/EffectListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/effects/FrozenListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/types/negative/FrozenEffect.java
Adds the frozen effect. While frozen, players cannot moving, attack, take damage, drop items, pickup items, break blocks, use skills, or anything else. They can chat.
The frozen punishment allows for staff to quickly prevent rule breaking players from continuing to act, before applying the appropriate punishment (a lot easier to freeze someone bunny hopping on someone, then type out the correct reason/time, rather than skip the frozen step).
Also allows staff to freeze a player and talk with them, for whatever reason.
Fixes #722
> Add Frozen effect and Punishment

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/fortune/FortuneT2.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/fortune/FortuneT3.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/frost/FrostT4.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/scorching/ScorchingT4.java
Some runes had an incorrect value for getTier, this now corrects the value that matches the name.
> Fix some runes having incorrect tier in code

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/RenameSubCommand.java
Fix clan rename by removing the old clan in the manager, and adding it back under the new name
Fixes #749
> Fix clan rename

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/Skill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/ArcticArmour.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Immolate.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/LifeBonds.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Void.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/ActiveToggleSkill.java
- champions/src/main/resources/configs/skills/skills.yml
All Mage active toggle passives now correctly use config values in terms of seconds. Energy draining is now consistent across all skills. Config values are updated to keep the same effect they had previously. Add energyStartCost config, which is the cost for activating the skill.
Arctic armour now updates at the same rate as other active toggle passives.
Arctic armour now has a start cost.
Fixes #751
> Update Mage Active Toggle Passives

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
When you apply build, track players is now called. This fixes flash and recall not working when switching from a build that does not have those skills, to a build with those skills
Fixes #748
> Fix track players not being called on apply build

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
If the chunk with the clanhome is unclaimed, sets the home to null and alerts the clan
Fixes #773
> Fix Clan Home existing in unclaimed territory

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/resources/clans-migrations/V1_1__Initial_clans.sql
Change getDominanceForKill to use the config for maxClanMembers, instead of using hardcoded 6
> Fix dominance using default value if size offset was too high

- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UUIDListener.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/PendingLog.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/ContainerBreakLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/ContainerStoreItemLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/ItemRetrieveLogFormatter.java
Fix container break logs to include client context. Add BlockState overload for adding a block context. Using this, now correctly gets the block that was broken.
Also fixes Item retrieve logs to include location
> Fix Container Break logs

- champions/src/main/resources/configs/skills/skills.yml
- Sets smokebomb cooldown to 40 (down from 50)
- This seems like a buff but its honestly more of a QOL, frequently you'll use the ability and finish a fight, go store and go back outside and then its still on cooldown
> smokebomb cooldown reduction

- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/Punishment.java
- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/commands/PunishmentHistoryCommand.java
Add basic punish history command. There isn't as much information as I'd like in it, but it's not worth adding that in during kit map. This will allow a temporary solution to allow admins to easily view the punish history of an account.
> Add Basic Punish History Command

- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UUIDListener.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/ItemRetrieveLogFormatter.java
Fixed there not always being block associated with a retrieve log. Add a fix to allow current logs to be read.
> Fix NPE in ItemRetrieveLogFormatter

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/ChannelSkill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/AlligatorsTooth.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/ThunderclapAegis.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/WindBlade.java
- champions/src/main/resources/configs/weapons/legendaries.yml
- core/src/main/java/me/mykindos/betterpvp/core/combat/weapon/types/ChannelWeapon.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
[Before](https://youtu.be/Rv4YYhUfX_c)
[After](https://youtu.be/g8aTTsNKnjo)
Updated movements to prevent canUse from removing players from the active set. Now it just returns before draining energy/applying abilities.
Since the player is still holding right click, the channel weapon check in [WeaponListener.java](https://github.com/Mykindos/BetterPvP/blob/master/core/src/main/java/me/mykindos/betterpvp/core/combat/weapon/listeners/WeaponListener.java) prevents them from becoming active again until they toggle right-click.
Relevant code from WeaponListener:
```
if (weapon instanceof ChannelWeapon channelWeapon) {
if (clicked.get(event.getPlayer().getUniqueId()) == weapon) {
return; // Skip if we're currently holding click on this weapon
}
if (channelWeapon.getEnergy() > 0) {
if …
```
> #417 - Fix movement legends

- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/data/PriorityDataBlockingQueue.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/display/ActionBar.java
Fix ActionBar components defaulting to null components when they have a higher priority, when an actual component exists that does not have a null value somewhere in the queue.
> Fix ActionBar using null elements when non-null elements exist in queue

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Sever.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Slash.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- [Make UtilEntity.IS_ENEMY ignore players in creative/spectator](https://github.com/Mykindos/BetterPvP/commit/b9ded139ea8ef0b2e64f4d2cdd943de40750ded8)
- [QoL slash changes and fix target selection](https://github.com/Mykindos/BetterPvP/commit/79069b00a8fb041bee4c75fbe5591082f50ea759)
- [Allow sever to hit entities](https://github.com/Mykindos/BetterPvP/commit/6fd015d94d804a005968a6d278d2c8cb6e21098e)
> Slash QoL, fix target selection, fix Sever

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/BuildManager.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/GamerBuilds.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/RoleBuild.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/listeners/BuildListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/BuildMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/ClassSelectionMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/SkillMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/ClassSelectionButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/DeleteBuildButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/EditBuildButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/RandomBuildButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/SkillButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/BuildCommand.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/admin/PromptBuildCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/button/BackButton.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/button/FlashingButton.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/listener/MenuListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
Add Flashing Button, which has elements for a button to change its go at a specified time. Extends Control Item.
Create a promptable build menu, that will flash on items that the user is intended to click on, until they successfully navigate to and create the build supplied to the menu. This will be used in the tutorial to teach player how to make a build.
Fixes #951
Fixes #952
> Promptable Build Menu

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/WoodcuttingHandler.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/event/PlayerChopLogEvent.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/WoodcuttingListener.java
- __Tree Feller__ didn't damage the tool or cause any durability so now this should fix that
- For every log felled, 1 durability is taken off
- Works with __Unbreaking Rune__
> Fix tree feller durability

- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UUIDListener.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/LogContext.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/LootSpawnItemLogFormatter.java
Add a log that uses the SpecialSpawnItemEvent to track UUIDItems being created from dungeons/events
Fixes #737
> Add a log for UUIDItems being looted from dungeons/events

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
stop teleport if it would hit the border
Completely cancel the teleport if it would hit the border. This allows the vanilla behavior when encountering the border to always work, and should always prevent players from getting past the border. Will stop the skill, but not use the skill. This only happens if it would hit the border (standing at the border and using a skill not directed at the border will still work).
Fixes #795
Fixes #1011
> Drastic fix to prevent passing the border

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
Smoke bomb ending gives a visual to the user, doesn't have the pick up rule like the old PR had
> Smoke Bomb Reappear Visual

- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/Gamer.java
- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/repository/GamerListener.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
Tracks players last movement, as there is no default way to get if a player is walking or not.
> Track player last movement

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- Fixed incorrect chat message when trying to equip armor from the hotbar while in combat
- Loosened the restrictions so that you can still right click armor from the hotbar while you have no armor equiped, but cannot while having armor equipped in that same type of armor slot.
> Fix armor swap message and functionality

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/Clan.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanBankListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanBannerListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEnergyListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanPropertyListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansChatListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansCombatListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansExplosionListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
- clans/src/main/resources/configs/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/framework/BPvPPlugin.java
- core/src/main/java/me/mykindos/betterpvp/core/listener/loader/ListenerLoader.java
Add a way to stop energy from draining for all Clans in config.
Now reload listeners for all plugins (allowing for them to use config changes)
Fixes #1059
> Add a way to pause energy, fix not reloading listeners.

- shops/src/main/java/me/mykindos/betterpvp/shops/auctionhouse/menu/buttons/CreateListingButton.java
Clone the item in main hand, to avoid errors when that item is moved while you are making an auction.
Fix #1149
> #1149 - Fix moving item from main hand causing errors

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
* Disabled picking up items while smoke bomb is active
* Before, picking up an item would end the vanish, but cleaning while vanished would totally not be broken or anything
https://github.com/Mykindos/BetterPvP/issues/1098
> Disallow item pickups while Smoke Bomb active

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/NapalmArrow.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/data/FireData.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
Fix issues with fire damage attribution causing players to not get kill credit when they should have. Prevent "random" players getting the kill instead
Fixes #1169 
Fixes #1170
> Fix Fire Damage Source Attribution causing incorrect kilers

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/commands/FishingExperienceCommand.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/mining/commands/MiningExperienceCommand.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/WoodcuttingHandler.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/commands/WoodcuttingExperienceCommand.java
Fix how durability was being handled in treefeller.
Add commands to each profession for admins to use to set experience, for testing
Fixes #1124
Fixes #1203
> Fix woodcutting durability handling, add profession experience admin commands

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
Always allow triggering tripwires
Allow crafting table use in admin clans
Fixes #1237 
Fixes #1178
> Fix tripwires and allow crafting table use in admin clans

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
- C stuck is a much less useful command than c home, and in general forces players to stay around dangerous areas instead of teleporting to safety. There is no reason why it should be significantly longer than a home teleport.
> Change c stuck timer to the same duration as c home

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Evade.java
Evade duration would be floored when casting to long before multiplication. Fixed by doing multiplication before casting.
- [X ] I have tested my changes.
> Fix evade duration truncating

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/blocktag/BlockTaggingListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/BarkBounty.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/WoodcuttingHandler.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/event/PlayerStripLogEvent.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/StrippedLogListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/WoodcuttingListener.java
- More cherry logs compatibility that was needed to get added
- There's still an edge case where if the player immediately chops the log after stripping (within 3 ticks), 0.0 exp will be awarded
- This edge case is realistically, only encountered when **Hyper Axe** is used
> Stripped Log Experience Fix

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/InvSeeCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/menus/PlayerInventoryMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/listener/MenuListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilInventory.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilNBT.java
Mock Minecraft inventory loading and saving of player data to access the inventory
> Add the capability to view and modify inventories offline

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/Fissure.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/FissureBlock.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/FissurePath.java
- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/RestoreBlock.java
- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java
Change how fissure stores blockdata (now correctly stores blockdata)
Change RestoreBlock to handle this functionality
Make RestoreBlock handle lily pads much better
Fixes #1234
> Fix Fissure breaking lily pads and pitcher plants

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/EnchantedLumberfall.java
Don't assign items with custommodeldata 0 a custom model data in Enchanted Lumberfall
Fixes #1419
> Fix Enchanted Lumberfall items not stacking with other items

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/protection/ClansProtectionListener.java
- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/listeners/GamerProtectionListener.java
Happens because you respawn in a safezone, which on leaving sets the last safe time, then updates your timer. Timer is updated on entering a territory, but no event is fired when you spawn in a safe area.
Fixes #1401
> Fix dying resetting protection timer

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/WhirlwindSword.java
Solve whirlwind sword doing damage to protected players due to it not using the correct way to apply damage.
Fixes #1402
> Fix whirlwindsword not doing damage correctly

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/Takedown.java
Revert ezrn's takedown nerf a while back. Should allow Takedown to actually catch up to targets now and have some viability alongside Seismic Slam
> Revert Takedown nerf

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/PestilenceProjectile.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Pestilence.java
- champions/src/main/resources/configs/skills/skills.yml
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/RayProjectile.java
- Fix https://github.com/Mykindos/BetterPvP/commit/68a6ad5b78025fd68c56b102979e1d34e19fe179 making all effective radiuses for all skills be `sqrt(radius)`
- Add a collision entity filter to `RayProjectile`
- Pestilence no longer weakens enemies
- Pestilence is now a channeled skill that fires a projectile.
- The projectile fired redirects toward the closest enemy and poisons them.
- Charging the skill increases the speed of the projectile (persists across target jumps)
- There is no target limit.
This change to Pestilence aims to add some skill expression and reduce its base power. To account for the power reduction, the poison duration was increased to (5 -> 6 -> 7 seconds)  and bumped to an amplifier of 2. (Deals 3 hearts to assassin at max level, just a little higher than before)
> Pestilence rework & some fixes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/AdminLogsSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/clans/ClanInviteLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/clans/ClanPromoteMemberLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/ItemDespawnLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/PlayerDeathItemLogFormatter.java
Fix an error with playerdeath item log, add location button to despawn log, fix some formatting errors in clan logs.
Add /c adminlogs <clanname|id>, allowing admins to view logs of clans they are not in, and allow them to see logs of clans by ID (i.e. a disbanded clan)
Fixes #1439
Fixes #1440
Fixes #1441
> Fix some item logs, clan formatters, allow admins to view logs by clan id

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Fortitude.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/BioticQuiver.java
- champions/src/main/resources/configs/skills/skills.yml
Ranger's kit identity is unclear—it isn't a tank like Knight or Brute, nor does it fully match the damage or utility of Mage and Assassin. While Ranger excels at supporting its team, with most bow abilities offering AoE advantages in team fights, two abilities, Biotic Shot and Mark of the Wolf, stand out for requiring direct hits to provide any value. Despite adjustments like larger hitboxes to make these abilities easier to land, players still often prefer other options like Tether, leaving these abilities underutilized.
The way to address Ranger's lack of a clear kit identity is by directly focusing on its most irrelevant skill, Biotic Shot.
**Bioitic Shot** was a bow skill that could deny enemies healing and regenerate massive amounts of health for allies:
After being reworked into a …
> Reworked Biotic Shot

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/MushroomStew.java
- core/src/main/java/me/mykindos/betterpvp/core/items/BPvPItem.java
- core/src/main/resources/configs/config.yml
Fix soup crafting being done incorrectly, by overriding crafting event. Now creates a custom recipe.
Fixes #1499
> Fix Crafters being unable to craft working soups.

- core/build.gradle.kts
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilFormat.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilTime.java
- core/src/test/java/me/mykindos/betterpvp/core/utilities/UtilFormatTest.java
- core/src/test/java/me/mykindos/betterpvp/core/utilities/UtilTimeTest.java
- core/src/test/java/me/mykindos/betterpvp/core/utilities/model/WeighedListTest.java
- settings.gradle.kts
I did this a while back, because I was bored. I ran into some issues using mockbukkit so set it aside. Picked it back up, fixed some things and got it working. Might as well put the work I did up.
Summary:
In test time, we need to exclude paperweight (see https://docs.mockbukkit.org/docs/en/user_guide/advanced/paperweight.html). This means we cannot test anything with NMS features.
We also cannot mock plugins (well, we might, but there are several issues that need to be resolved. MockBukkit proxy's the plugin class, so we cannot access getClass().getPackageName(). There are also problems with accessing resources (aka configs) and databases that need to be resolved).
This means that we can only test things that use the Bukkit static classes.
> Add more unit tests + mockbukkit

- game/src/main/java/me/mykindos/betterpvp/game/gui/hotbar/ButtonHotBarSlot.java
Since there is no way exit choosing an item for a slot, users sometimes will close the inventory to try and get back to the previous screen, losing them their progress. On closing the selector, it will now show the editor (where users can cancel or save their hotbar), leading to more intuitive user flow.
> On closing HotBarItemSelector, show the hot bar editor

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/roleeffects/AssassinListener.java
- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/listener/FlagHolderListener.java
- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/Flag.java
- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagPlayerHandler.java
Prevent flag holders from gaining the speed effect, prevent flag holders from losing the speed effect (cleanse etc.).
Picking up the flag will remove smoke bomb's vanish
Fixes #1541
Fixes #1542
> No speed and no smokebomb on flag pickup

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEnergyListener.java
- core/src/main/java/me/mykindos/betterpvp/core/components/clans/events/ClansDropEnergyEvent.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/EffectManager.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/listener/FishingListener.java
Change ClansDropEnergyEvent to take a LivingEntity (i.e. killer/block breaker/fisher).
If that entity is a player and has protection, reserve the dropped item
Must also merge https://github.com/Mykindos/BetterPvP-Private/pull/54
Fixes #1554
> Fix being unable to pickup energy from breaking blocks while in protection

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilPlayer.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/team/TeamDamageListener.java
FetchNearbyEntityEvent was not being handled correctly by TeamDamageListener, it only set if friendly, it also needs to set if enemy.
Functions that used FetchNearbyEntityEvent were not checking if the entities being fetched actually matched the desired property.
Fixes #1571
> Prevent skills that only work on allies affect enemies and vice versa

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagPlayerHandler.java
An interaction between Long.MAX_VALUE and resilience was causing flag slow to not effect those players
> Fix resilience removing flag slowness

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/MagneticAxe.java
Drop magneticaxe through the minecraft Player#Drop function, to allow plugins to cancel the event. This allows games to prevent the drop of an axe if the player inventory if full or if the player died.
Fixes #1584
> Magnetic Axe drop now triggers a drop event

- game/src/main/java/me/mykindos/betterpvp/game/framework/manager/MapManager.java
Prevent players playing the same map back to back. Any other map is valid and allows for a gamemode with 1 map.
Fixes #1611
> Prevent playing the same map back to back

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/Rupture.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/HolyLight.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Immolate.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Blizzard.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/AlligatorsTooth.java
- champions/src/main/resources/configs/skills/skills.yml
> # Champions Release 2025-05-08
> 
> ## Combat
> - Remove Pin effect from Gator Strike (Alligator's Tooth)
> 
> ### Brute
> - Skullsplitter base bleed seconds 4 → 2 Seconds
> 
> ### Mage
> - Fix Pestilence travel speed
> - Remove Ice Prison center dome gap
> - Increase Ice Prison cooldown from 25 → 26 seconds
> - Disable Fissure
> - Rework Blizzard to have pushback and more horizontal velocity
> - Rework Rupture to use display entities and fix its trajectory
> - Reduce Rupture slowness strength 3 → 1
> - Increase Rupture slowness duration 1.5 → 3.0 Seconds
> - Decrease Rupture base damage 8.0 → 6.0 HP
> - Increase Rupture damage per level 0 → 0.5 HP
> - Decrease Void base energy usage 28 → 24 energy per tick
> - Decrease Void damage reduction 2.0 → 1.5 HP
> - Increase Void energy …
> Mage Buffs & Fixes

- game/src/main/java/me/mykindos/betterpvp/game/command/SpectateCommand.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/team/TeamBalancerHandler.java
Prevent using /spec in combat and alive 
Use respawn timer to determine how long to move a player from spectator to play
Fixes #1708
Fixes #1709
> Fix Spectator Shenanigans 

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagBlock.java
Make flag display block glow, to make it easier to find the flag in general, and when dropped in particular
> Make flag DisplayBlock glow

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/Skill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/SeismicSlam.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/Skullsplitter.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/Takedown.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/FastRecovery.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/LevelField.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Deflection.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Swordsmanship.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/PassiveSkill.java
Prevent holy light, seisimic slam, takedown, and skullsplitter from activating in while in spectator. PassiveSkills are disabled by default, but certain skills like deflection and swordsmanship are enabled.
> Prevent using most passive skills while in spectator. Prevent some delayed actions skills from triggering in spectator

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/VanguardsMight.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/ChannelSkill.java
- note: because of the way that `ChannelSkill` works, you *can* kind of use the skill in water. `ChannelSkill` only "cancels" it if the player moves around in water so if you drop directly into water and don't change your block, you can still keep using it.
> fixed bug where vanguards might would break after being cancelled

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/data/VanguardsMightData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/VanguardsMight.java
- champions/src/main/resources/configs/skills/skills.yml
- Changed action bar messages to look **a lot** cleaner (no longer uses purple text).
- Changed strength effect duration scaling to be `3.0 -> 5.5 -> 8.0` instead of `6.0 -> 7.0 -> 8.0`
- Vanguards Might now passively charges `50` charge per second
https://medal.tv/games/minecraft/clips/l6tKjeBJDTHBCv5Hj?invite=cr-MSxtUGQsMzk5NTIyMjcw&v=15
> Vanguards Might QoL & Improvement
