- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/WolfsPounce.java
- champions/src/main/resources/config.yml
Changes:
- Added mostly 1:1 replica of [Wolfs Pounce](https://i.imgur.com/k8K0Kya.mp4) skill from Mineplex. Only differing qualities are sound and charging bar.
> Create Wolfs Pounce skill

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/ShieldSmash.java
- champions/src/main/resources/config.yml
Changes:
- Added 1:1 replica of [Shield Smash](https://i.imgur.com/vq1UmLP.mp4) skill from Mineplex.
> Create Shield Smash skill

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/BloodBarrier.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/TormentedSoil.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Impotence.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Siphon.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/sword/Leech.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/sword/Wreath.java
- copytoserver.ps1
Pass through for Warlock, updated a lot of skills to use config values, updated skill descriptions.
> Warlock skill/config

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/axe/Boulder.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/data/BoulderObject.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/WolfsPounce.java
- champions/src/main/resources/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
Changes:
- Create new [Boulder](https://i.imgur.com/0QKLIcl.mp4) skill
still needs some perfecting of the pebbles' gravity
> Create Boulder skill

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/SkillManager.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/sword/Polymorph.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/sword/StaticLazer.java
- champions/src/main/resources/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
Changes:
- Create 1:1 Mineplex replica of [Static Lazer](https://i.imgur.com/KCbouul.mp4) skill
- Create utility method to check if a bounding box collides with the collision shape of a block.
- Disable Polymorph to fit new Static Lazer skill
> Create Static Lazer skill

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SilencingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/gladiator/axe/ThreateningShout.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/gladiator/passives/Colossus.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/gladiator/passives/CripplingBlow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/gladiator/passives/Stampede.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/gladiator/sword/Takedown.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/BreakFall.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/FastRecovery.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/BullsCharge.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/HoldPosition.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/LevelField.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/axe/Rupture.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/sword/Pestilence.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/axe/Agility.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/Disengage.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/WolfsPounce.java
- champions/src/main/resources/config.yml
Also some minor description formatting.
> Unified how percentages are handled in Config

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/events/RoleChangeEvent.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/Skill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/data/FlashData.java
- champions/src/main/resources/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/VectorLine.java
Changes:
- Improve Flash skill to have better collision checks and be more lenient to players.
- Allow skills to track what players are using their ability from the time they equip it to when they unequip it.
- Create utility methods to allow for collisions checks with bounding boxes
- Create VectorLine.java, which can allow to obtain points / locations within that line.
Changes were *mostly* tested
> Improve Flash Skill and utility changes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/AssassinListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ViperStrikes.java
- champions/src/main/resources/config.yml
Changes:
- Create 1:1 replica of Viper Strikes from Mineplex
- Fix Assassin's speed to correctly display permanent duration
> Create Viper Strikes skill and fix Assassin speed

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/SkillMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Blink.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/MarkedForDeath.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/SilencingArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/SmokeArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/ToxicArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Recall.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/RepeatedStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SilencingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Sever.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/FastRecovery.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/axe/DefensiveAura.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/axe/LightningOrb.java
Adding <effect> (white) for potion/status effects and <stat> (yellow) for static, non changing values.
4th pass for Assassin, including these new Tags.
> Add new format options for skill descriptions

- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/WeighedList.java
- core/src/test/java/me/mykindos/betterpvp/core/utilities/model/WeighedListTest.java
Changes:
- Create `WeighedList.java`, a utility wrapper for a collection that allows to obtain a random element off a list based on a weighed element within a weighed category. The effective probability of getting an element is `(Weight of the category / Total weights of all categories) * (Weight of the element / Total weights of all elements in that category)`.
- Create a test for `WeighedList.java`
> Creat weighed pool system for loot tables, random element generation, etc

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/data/SkillWeapons.java
- champions/src/main/resources/champions-migrations/V2__Armour_weapon_values.sql
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- shops/src/main/resources/shops-migrations/V2__Create_default_shopitems.sql
To keep it consistent with Mineplex's game and to not confuse the rest of the audience
> Swap booster and extra-damage weapons

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/ClanSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/AddOutskirtsSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClanHelpSubCommand.java
Added a page system for help command.
Added looking up a specific command.
Sorted commands by name.
Draft because I have more features in mind, but do not want other people to do work I have already done.
> Update /c help.

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
- champions/src/main/resources/config.yml
> added mineplex vengeance ability to clans

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/passives/LifeBonds.java
- champions/src/main/resources/config.yml
> added life bonds ability from mineplex

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/chatcommands/AllyChatCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/chat/ChatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/StaffChatCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/gamer/GamerManager.java
/staffchat, similar to /clanchat or /allychat
> Added staff chat

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/Clan.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/chatcommands/AllyChatCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/chatcommands/ClanChatCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansChatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/chat/ChatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/StaffChatCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/gamer/GamerManager.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilPlayer.java
Implements #86. All commands now accept an optional [message], which if provided instead sends the message instead of toggling. Refactored how messages were sent to reduce duplicate code.
> Implement #86 (message optional for chat toggle)

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/axe/Boulder.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/paladin/data/BoulderObject.java
- champions/src/main/resources/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/DisplayEditorManager.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayDeselectSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayInterpolationSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayRemoveSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayRotateSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayScaleSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplaySelectSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplaySummonSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayTransformSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/display/command/DisplayTranslateSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilMath.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilPlayer.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/math/Function3d.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/math/VectorLine.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/math/VectorParabola.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/model/Bait.java
Changes:
- Create utility display entity editor. `/display`
- Create utility math function classes
- Fix Boulder animations, radius and player effects
> Create math function and display entity utilities. Complete Boulder ability

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/AddOutskirtsSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClanRecoveryCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/SetDominanceSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/SetEnergySubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/SetSafeCommand.java
Also added some error handling to some commands. Partial implementation of #87.
The rank that it sends to is subject to change, it should at minimum be Rank.ADMIN, just for logging and information purposes.
> Added messages to staff doing admin actions

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClanHelpSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ListSubCommand.java
Implements #93 and #92. Adds a page number for /c list and /c help. Adds /c to all /c help commands.
> Update /c list and /c help to have pageNumbers

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/HeavyArrows.java
-no longer works while in water, stunned, or silenced
-energy now scales based on arrow charge like knockback
> fixed heavy arrows

- core/src/main/java/me/mykindos/betterpvp/core/chat/ChatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/client/Rank.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/AdminMessageCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/AdminReplyCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/StaffChatCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/PlayerAdminCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/gamer/Gamer.java
Implements #88 and finishes implementing #89.
> add /ra and /admin

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClaimSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/DemoteSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/UnclaimSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
Continues implementing #100, adds logging for creating an admin clan, prevent a claim from being overclaimed, joining a clan.
> More logging of admin actions

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/HeavyArrows.java
-works while silenced again(its a passive)
-no longer consumes energy while crouched
> fixed heavy arrows(again)

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/data/RiposteData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/Riposte.java
- champions/src/main/resources/champions-migrations/V2__Armour_weapon_values.sql
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- champions/src/main/resources/config.yml
- core/src/main/resources/core-migrations/V1__Initial_core.sql
-Now has a maximum cast time(configurable)
-Reduced damage and knockback by 100% and allows the user to parry
-If the parry is successful it will deal up to 3 extra damage and heal up to 3 extra health(configurable)
-Parry extra damage expires after 2 seconds
> Riposte Rework

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/ToxicArrow.java
- Removed nausea aspect because players can turn off nausea effects in settings
- Made the arrow give Poison 2 instead of Poison 1 as compensation
> redistributed power in toxic arrow

- clans/src/main/java/me/mykindos/betterpvp/clans/combat/CombatTagListener.java
- now will be crit particles directly above the players head that play every second
- particles will only play while players are in safe zones
- added configurability so that the particles can be given a radius
> modified combat tag particles to work like mineplex

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/GlacialPrison.java
- champions/src/main/resources/config.yml
- angry mineplex players can be happy now
> added hole to ice prison

- core/src/main/java/me/mykindos/betterpvp/core/combat/hitbox/HitboxHandler.java
Spark profiler from server start using a 50 cps autoclicker: https://spark.lucko.me/tqZo6cbdCW
> Use ray tracing for hitboxes and fix kindos' back-hits

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/BroadcastCommand.java
> add a broadcast command for staff

- clans/src/main/java/me/mykindos/betterpvp/clans/combat/CombatTagListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
- When you enter a safe zone, you will get a "Safe!" message in the middle of your screen
- When entering a safezone while combat tagged, a countdown will display on your screen telling you how long you are unsafe for.
- This only displays in safezones
> added safe and unsafe subtitle displays like mineplex

- clans/src/main/java/me/mykindos/betterpvp/clans/commands/commands/ClansCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/ClanTip.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/ClanTipListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanCreateTip.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanEnergyTip.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanHelpTip.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanHomeTip.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanInviteTip.java
- core/src/main/java/me/mykindos/betterpvp/core/tips/Tip.java
- core/src/main/java/me/mykindos/betterpvp/core/tips/TipListener.java
- core/src/main/java/me/mykindos/betterpvp/core/tips/TipManager.java
Partial implementation of #140 
Adds the following config options for tips
- Enabled
- weight
- weightCategory
> Add config to Tips

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Blink.java
- Fixed strange smoke particle orientation when blinking diagonally
> fixed blink particles

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/Rupture.java
- Now takes the sounds and visuals of the blocks below it to make the rupture instead of using ice
> made rupture look epic

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/Skill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/CooldownSkill.java
- core/src/main/java/me/mykindos/betterpvp/core/components/champions/ISkill.java
> Fix overlap of ability cooldown displays when switching classes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Evade.java
- champions/src/main/resources/config.yml
- Base configurable cooldown
- Still scales on handRaisedTime
> made evade changes on separate branch

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/HiltSmash.java
- When not clicking on a player, hilt smash now will miss and activate the cooldown
- Same previous functionality still applies
> Made hilt smash able to miss

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/data/RecallData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Recall.java
- champions/src/main/resources/config.yml
- Now has a trail that tracks where the player was over the last x seconds
- Looks beautiful
> made recall trail

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/Clan.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/BannerSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/events/ClanBannerUpdateEvent.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/leaderboard/ClanLeaderboard.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanBannerListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/BannerMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/ClanMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/ClanDetailsButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/ViewClanButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/banner/AddPatternItem.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/banner/CancelItem.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/banner/PatternItem.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/banner/PreviewItem.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/banner/SaveItem.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/repository/ClanRepository.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/button/BackButton.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/impl/GuiSelectColor.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/impl/GuiSelectPattern.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/item/banner/BannerColor.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/item/banner/BannerWrapper.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/item/skull/SkullBuilder.java
- progression/src/main/java/me/mykindos/betterpvp/progression/tree/fishing/bait/SimpleBaitType.java
Changes:
- Add a reusable `GuiSelectColor`
- Add a reusable `GuiSelectPattern`
- Add `BannerMenu` ([example](https://i.imgur.com/yjnJATz.gif))
Changes were testred
> Clan banner editor menu

- core/src/main/java/me/mykindos/betterpvp/core/items/enchants/GlowEnchant.java
Solve errors being generated by GlowEnchant.
> Fix GlowEnchant not overriding needed methods

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/legendaries/MagneticMaul.java
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- champions/src/main/resources/config.yml
- core/src/main/java/me/mykindos/betterpvp/core/combat/events/CustomKnockbackEvent.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
> Magnetic Maul

- champions/src/main/java/me/mykindos/betterpvp/champions/commands/ChampionsCommand.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/Weapon.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/WeaponManager.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/legendaries/GiantsBroadsword.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/legendaries/KnightsGreatlance.java
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- core/src/main/java/me/mykindos/betterpvp/core/components/champions/weapons/IWeapon.java
> Giant's Broadsword

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/Skill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/ActiveToggleSkill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/ChannelSkill.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
#78, #164 #237 Fix skills remaining active when they should not, fix some instances of being able to use skills in water (prevents it specifically for 1 deep water)
> Fix skills continuing when status is invalid, fix using skills in 1 deep water when not intended,

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/Disengage.java
- champions/src/main/resources/config.yml
- Disengage now uses a channel based activation system instead of a prepare system
- Prevents attacking while using the skill
> Fix disengage bug

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Cyclone.java
> added cool particles to cyclone

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
> Prevent clan's subcommands from being a clanname

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/combat/ClansSkillListener.java
#209 Changed checking canHurt to new function, isAlly.
> Change how onFetchNearbyEntity populates

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/qol/TeleportPositionCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
> Move ~ handling to UtilLocation

- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
Changes:
- Make true damage sources work as expected
Fixes #248
> Fix true damage sources

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/Takedown.java
> Move Takedown to axe

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/BloodCompass.java
- champions/src/main/resources/config.yml
- Tested with one target, needs testing with multiple
- Passive A bug needs to be fixed, and then this ability needs to be moved to passive A
> Add Blood Compass

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/LevelField.java
- champions/src/main/resources/config.yml
- (0.5 * Level) extra dealt damage and less received damage per player outnumbered within a radius
- Drop item functionality that locks in values for a set time and has a cooldown
- Actionbar component that displays the number of enemies that outnumber you on-screen with a customizable cap
- Mostly tested
> Level Field Rework/Fix

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Thorns.java
- added internal cooldown in description
> made thorns description match behavior

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/SeismicSlam.java
- champions/src/main/resources/configs/skills/skills.yml
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilVelocity.java
- Shorter and more controlled jump with a more visible impact radius on the ground
- Numbers might need some work as the distance scaling is a bit different than it used to be
> 1:1 seismic slam copy

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Immolate.java
- champions/src/main/resources/configs/skills/skills.yml
- Made it identical to mineplex(gives strength but less speed)
- Also added some cool fire particles
> Immolate change and particles

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
> Fix /c promote and /c demote feedback indicating running command player was the one demoted (when not the case)

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Intimidation.java
> Update intim tooltip

- core/src/main/java/me/mykindos/betterpvp/core/client/commands/ClientCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/InvSeeCommand.java
> Add playername tabcompletion to promte/demote and invsee

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/CustomEffectCommand.java
> Fix customeffect not applying to target

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/weapons/ThrowingWeb.java
> Fix left click not giving cooldown for throwing_web

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/PowerChop.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/LevitatingShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/PinDown.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Frailty.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Impotence.java
- champions/src/main/resources/configs/skills/skills.yml
Fixes #347, fixes #339, fixes #332, fixes #364,
> misc changes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClanHelpSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/UntrustSubCommand.java
> Remove extraneuous lines in /c help

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/RoleSoundProvider.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ViperStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/SeismicSlam.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/FleshHook.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/MagmaBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/StaticLazer.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/BankSubCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/damagelog/DamageLogListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/damagelog/DamageLogManager.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/data/SoundProvider.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/events/CustomDamageEvent.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/EffectListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/scoreboard/ScoreboardListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilMessage.java
Fixes #380, fixes #382, fixes #371, fixes #415, fixes #394, fixes #381, fixes #383, fixes #390, fixes #389, fixes #398, fixes #395, fixes #412, fixes #393
> Miscellaneous fixes 1.22.24

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/CustomGiveCommand.java
> Add multiple items to customgive

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/MarkedForDeath.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/SilencingArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/SmokeArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/bow/ToxicArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Bloodlust.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/HealingShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/IncendiaryShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/LevitatingShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Overcharge.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/PinDown.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/RopedArrow.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StunningShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Volley.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/Longshot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/Sharpshooter.java
- champions/src/main/resources/configs/skills/skills.yml
- #404 
- #419 
- #416 
- #427 
- Added unique and differentiable particle effects to every special arrow
- All assassin arrow effects look like "potions" for better differentiability from ranger arrows
- Misc other issues fixed
> arrow particles and misc fixes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/PrepareArrowSkill.java
> Fix special arrows causing cooldowns

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/LifeBonds.java
- champions/src/main/resources/configs/skills/skills.yml
Added travel time
- fixes #453
> life bonds

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/ClassSelectionMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/ClassSelectionButton.java
Add ehp/damage reduction to build menu
Fixes #486
> Add ehp/damage reduction to build menu

- core/src/main/java/me/mykindos/betterpvp/core/items/BPVPItem.java
> Fix all music disks becoming legends

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/FireBlast.java
- champions/src/main/resources/configs/skills/skills.yml
- Made fireblast function like mineplex
> Fire Blast Changes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Fortitude.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/HealingShot.java
adds a visual to both skills and adds the sound that played on mineplex to healing shot
> fortitude and healing shot visuals/audio

- core/src/main/java/me/mykindos/betterpvp/core/Core.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/mythicmobs/DamageIndicator.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/mythicmobs/DamageIndicatorAdapter.java
Add damage indicators on MythicMobs entities whenever they take damage to a player
> Damage indicators for MM

- core/build.gradle.kts
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientExpiry.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
- core/src/main/java/me/mykindos/betterpvp/core/database/Database.java
- core/src/main/java/me/mykindos/betterpvp/core/database/mappers/PropertyMapper.java
- core/src/main/java/me/mykindos/betterpvp/core/database/query/values/TimestampStatementValue.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/PluginAdapter.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/PluginAdapters.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/button/BackButton.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/impl/ConfirmationMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/impl/ViewCollectionMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/AbstractPacket.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/clientbound/WrapperPlayServerEntityEquipment.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/clientbound/WrapperPlayServerEntityMetadata.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/clientbound/WrapperPlayServerKickDisconnect.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/clientbound/WrapperPlayServerOpenWindowMerchant.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/clientbound/WrapperPlayServerSetSlot.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/clientbound/WrapperPlayServerWindowItems.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/serverbound/WrapperPlayClientSetCreativeSlot.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/serverbound/WrapperPlayClientUseItem.java
- core/src/main/java/me/mykindos/betterpvp/core/packet/play/serverbound/WrapperPlayClientWindowClick.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilConverter.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilInventory.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/item/ItemView.java
- settings.gradle.kts
https://github.com/Mykindos/BetterPvP-Private/issues/10
https://github.com/Mykindos/BetterPvP-Private/issues/10
> Store private module framework

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/RootingAxe.java
- champions/src/main/resources/configs/skills/skills.yml
replicated glacial blade from mineplex
> glacial blade and rooting axe description fix

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Fury.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
- champions/src/main/resources/configs/skills/skills.yml
- Made vengeance like it was on mineplex
- Made fury like current vengeance so that its skill based
> fury vengeance changes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Sever.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/BullsCharge.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/HiltSmash.java
- champions/src/main/resources/configs/skills/skills.yml
- Fixed sever and hilt smash sounds + logic
- Fixed sever cooldown not properly scaling
- Reach distance also fixed(?)
> hilt and sever fixes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/AssassinListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Leap.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/SeismicSlam.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/RopedArrow.java
- Added new methods to leap, seismic slam, and roped arrow to prevent fall damage based on certain criteria
- Removed fall damage immunity from assassin
> removed fall damage immunity from assassin

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/Longshot.java
- champions/src/main/resources/configs/skills/skills.yml
- Made longshot start at 1 damage
- Increased other damage portions of the skill to compensate
> longshot change

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Void.java
- champions/src/main/resources/configs/skills/skills.yml
- made void reduce energy based on damage dealt to the player instead of per hit
- Fixes #538
> Void mage fix

- champions/src/main/resources/configs/skills/skills.yml
Changed all remaining passives to be level 3 max like all the other ones
- Holy Light
- Stampede
- Bloodlust
- Bloodthirst
- Heavy Arrows
- Hunters Thrill
- Siphon
> Changed remaining passives to level 3

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Fury.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
- champions/src/main/resources/configs/skills/skills.yml
- They were both doing unintended amounts of damage
> fixed glacial and fury damage

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/WolfsPounce.java
- Still is unusable in the air, but when jumping on flat ground or while hanging off sides of blocks it will correctly charge
> allowed wolfs pounce to charge while jumping

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/Fissure.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/FissureBlock.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/FissureCast.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/FissurePath.java
- champions/src/main/resources/configs/skills/skills.yml
- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/RestoreBlockListener.java
Mostly a copy of fissure from Mineplex with a few major improvement to how it navigates terrain
> Fissure Skill

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Blink.java
@Mykindos in your previous fix you only put the velocity reset in deblink
> fixed blink fall damage

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Leap.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/SeismicSlam.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/RopedArrow.java
Fixed errors introduced when non-players take fall damage
> Fix unchecked cast to Player in reduceFallDamage methods

- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/EffectListener.java
> added effects for bleed

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/data/BlockTossObject.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/BlockToss.java
Fix BlockToss yaw, size and detection
https://github.com/Mykindos/BetterPvP/issues/557
> Fix BlockToss yaw, size and detection

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Inferno.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/StaticLazer.java
- champions/src/main/resources/configs/skills/skills.yml
- Fixed static lazer not reducing energy per level
- Fixed inferno spread(forgot to add a 0 last time)
- Made inferno use energy, decreased cooldown back to original
- Fixed blizzard energy
- Fixed glacial blade not consuming energy
> mage fixes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/TutorialSubCommand.java
Change to use Role#getDescription
Add information about enchant tables
> Update /c tutorial

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/Disengage.java
- champions/src/main/resources/configs/skills/skills.yml
- Lowered disengage velocity
- Made it decrease cooldown per level
> lowered disengage velocity

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Evade.java
- champions/src/main/resources/configs/skills/skills.yml
- Made evade scale the internal cooldown based on level so there an actual reason to upgrade it
- Capped the level at 3 instead of 5
> changed evade scaling

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scepter/BlackHole.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scepter/Scepter.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scepter/ScepterListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/Scythe.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/ScytheData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/ScytheListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/Soul.java
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- Create Meridian Scepter
- Move Black Hole mechanic to Meridian Scepter
- Add soul harvesting mechanic to Scythe
https://github.com/Mykindos/BetterPvP/issues/283
> Add Meridian Scepter, Rework scythe

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Fortify.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/BlockToss.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/FleshHook.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/Riposte.java
-Make Flesh Hook use config values in skill implementation
-Fix fortify percvent (level 1 used to have a 0% change and all changes were shifted down by 10%)
-Fix block toss description (Block toss had a negative cooldown value from level 3 and above and changing "Recharge" to "Cooldown" keeps consistency 
https://github.com/Mykindos/BetterPvP/issues/481
> Brute Fixes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/axe/WolfsFury.java
-Wolfs Fury didn't disable the players strength upon the skills expiration beforehand
> Fix Wolfs Fury

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Backstab.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SilencingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Overwhelm.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/FleshHook.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Sacrifice.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Swordsmanship.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/FireBlast.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/MagmaBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/IncendiaryShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/PinDown.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/Precision.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/sword/Grasp.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/sword/Leech.java
- champions/src/main/resources/configs/skills/skills.yml
> fix all skills broken by the level change

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Stampede.java
- champions/src/main/resources/configs/skills/skills.yml
- Taking damage cancels stampede
- Knockback scales per stampede level
- Max level of 3
- Speed goes up faster
> Changed stampede to mineplex version

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/KnightsGreatlance.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilVelocity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/math/VelocityData.java
- Fix lance resetting fall distance
- Add velocity data field to toggle fall distance reset
Fixes #597
> Fix velocity fall damage

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/LevelField.java
- champions/src/main/resources/configs/skills/skills.yml
> Level Field Old

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/SendSkills.java
Adds a command to send your skills to your current chat channel (i.e. public, clan, ally). This sends it like it was a message.
https://prnt.sc/8f03OHQuB_o-
https://prnt.sc/ECPuUlD1Q1Mn
https://prnt.sc/3H3L7QGNMQgr
Fixes #626
> Add a command to share your current build with others.

- clans/src/main/java/me/mykindos/betterpvp/clans/world/WorldListener.java
Allow players to light candles and cake candles with flint and steel
Fixes #621
> #621 - Allow players to light candles

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/SendSkills.java
Fixes sendskills in public chat formatting for Helper+
Fixes #636
> Fix sendskills formatting

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UuidListener.java
Allow players to drop items from inventory view without triggering toggle skills
Allow legends to toggle toggle skills
Fixes #632 
Fixes #627
> Toggle skill drop QOL

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/data/FlashData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/data/WreathData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/sword/Wreath.java
- champions/src/main/resources/configs/skills/skills.yml
- Made wreath have a charge system like flash
> Wreath Rework

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/RopedArrow.java
- champions/src/main/resources/configs/skills/skills.yml
- Shorter cooldown
- Much less velocity
- Enabled its use while slowed since its much weaker now
- Fixes most of #426
> made roped arrow like mineplex

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Slash.java
- champions/src/main/resources/configs/skills/skills.yml
- core/src/main/java/me/mykindos/betterpvp/core/cooldowns/CooldownManager.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/MultiRayTraceResult.java
- New sword ability for assassin
> Slash Skill

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/RoleBuild.java
Change from "Click here to show descripton" to actual description in build component.
> Change /skills to show description on hover

- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UUIDListener.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/commands/LegendLogSubcommand.java
Fix some issues with legend logs
> Fix contributing log having incorrect formatting

- core/src/main/java/me/mykindos/betterpvp/core/client/properties/ClientProperty.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientListener.java
- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UUIDListener.java
- core/src/main/java/me/mykindos/betterpvp/core/settings/menus/GeneralSettingsMenu.java
- core/src/main/resources/core-migrations/global/V1__Initial_global_core.sql
Prevent dropping UUIDItems unless you drop it twice within a specified time period (currently 500ms).
Fixes #609
> Add drop protection for UUIDitems

- core/src/main/java/me/mykindos/betterpvp/core/effects/EffectManager.java
> Fix NPE in getEffect

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/SearchCommand.java
Update /search online to online show players that have legends, to increase readability
Fixes #670
> Update search online

- core/src/main/resources/core-migrations/local/V3__Logging.sql
Fix SQL error generated by a typo in GetUuidLogsByPlayer
> Fix typo in GetUuidLogsByPlayer

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
Fixes data truncation erros, by explicitly using the datatypes that make up a location in the database
Fixes #695
> Fix clan sethome errors in the database

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/RoleBuild.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/SkillButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/SkillDescription.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/Skill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/InventorySkillListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillChatListener.java
[Make skill lore in items packet-based](https://github.com/Mykindos/BetterPvP/commit/662ff506520dbce28580eb0e68e812e55febd4a0)
Fixes https://github.com/Mykindos/BetterPvP/issues/694
> Make skill lore in items packet-based

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/data/BullsEyeData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/Bullseye.java
Improve the color of the particles in the Bulls Eye skill and fix a bug where particles would still be spawned even if the target has died (or is invalid)
> Fix Bulls Eye color and bugs

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/FastRecovery.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Cleave.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Swordsmanship.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Immolate.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Swarm.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Overcharge.java
- champions/src/main/resources/configs/skills/skills.yml
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/map/listeners/MapCursorListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/BPvPPlugin.java
- core/src/main/java/me/mykindos/betterpvp/core/items/listener/ItemListener.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/DefaultResourcePackLoader.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/IResourcePackLoader.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/ResourcePack.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/ResourcePackHandler.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/ResourcePackListener.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/commands/LoadPackCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/resourcepack/exceptions/ResourcePackShaException.java
- core/src/main/resources/configs/config.yml
- core/src/main/resources/configs/resourcepacks.yml
Reverts Mykindos/BetterPvP#710
> Revert "Skill bug fixes and Map improvements"

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/FastRecovery.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Cleave.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Swordsmanship.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Immolate.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Swarm.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Overcharge.java
- champions/src/main/resources/configs/skills/skills.yml
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/map/listeners/MapCursorListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
> Musclemans changes

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/EnergyApple.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/vanilla/EnergyElixir.java
- champions/src/main/resources/champions-migrations/V4__Add_items.sql
- champions/src/main/resources/configs/weapons/standard.yml
-Nerf energy apple and add the energy it gives in its description
-Add energy elixir, the upgraded version of the energy apple (also has energy given in its description)
https://github.com/Mykindos/BetterPvP/issues/661
> Add Energy Elixir

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/RestoreBlock.java
- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/RestoreBlockListener.java
- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java
Break IcePrison with shift-click
#689
> Break IcePrison with shift-click

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/menu/KitButton.java
Change /kit from resetting full inventory, only giving an iron sword / iron axe / book / bow if the player does not have it in their inventory
Fixes #719
> Update /kit to not reset inventory

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/admin/LegendsCommand.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/admin/RunesCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/items/ItemHandler.java
Add /legends and /runes, admin commands that will either spawn all legends, or spawn runes of the specified tier.
Fixes #730
Fixes #731
> Add /legends and /runes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/BuildSkill.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/InventorySkillListener.java
> Fix Booster Items not showing increase skill level

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Pestilence.java
Changed description of Pestilence 
#741
> Fixed #741 - Updated description of pestilence skill.

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/SendSkillsCommand.java
Added a coioldown for using /sendskills, add an additional alias
Fixes #738
> Add a cooldown for using /sendskills

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/BuildMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/ApplyBuildButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/DeleteBuildButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/EditBuildButton.java
-Added confirmation when deleting builds.
-Added preview dialog when hovering over different builds.
-Made it so when you edit a build you also select the build at the same time.
> Class Selector - QoL changes

- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/commands/PunishmentAddCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/commands/PunishmentRemoveCommand.java
Add logs/feedback for punishment add and remove. On remove, a message will be sent to all online staff. Made punish add require the unit to be specified (fixes a possible IndexOutOfBoundsException)
Fixes #750
> Add logs/feedback for punishment add and remove

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
Fix how clan join logs apply context, allowing them to display logs correctly
Fixes #756
> Fix clan join logs

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Leap.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Volley.java
Update volley description to be more accurate. Add slow condition to assassin movement ability descriptions
Fixes #742
> Update Assassin movement and Range volley descriptions

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/StuckSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanStuckTip.java
Fixed /c stuck command cooldown, fix /c stuck tip using /c unstuck. Also, make it an always valid tip.
Fixes #777
Fixes #778
> Fix /c stuck related issues

- core/src/main/java/me/mykindos/betterpvp/core/items/listener/UUIDListener.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/BuyItemLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/SellItemLogFormatter.java
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/listeners/ShopListener.java
Add logs for buying/selling UUID Items (legends, cannons).
Add InventoryType.CRAFTING to INVENTORY_NO_STORE_TYPES
Fixes #767
Fixes #763
> Add logs for buying/selling UUID Items

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/sword/Wreath.java
[Fix Wreath granting health for multiple fangs](https://github.com/Mykindos/BetterPvP/commit/6acdb74914fa77675492c4bb8ac08ef805d0bcf2)
> Wreath Hotfix: Granting health for multiple fangs

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/data/FlashData.java
Fix Flash going negative charges
> Fix Flash going negative charges

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/data/FlashData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/scythe/ScytheListener.java
> Potentially fix lag

- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/Gamer.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/sidebar/SidebarController.java
> Potentially fix sidebar

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/PlayerAdminCommand.java
Add a cooldown for muted players
> Add a cooldown for using /a if muted

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/DefensiveAura.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/EffectManager.java
Fix Defensive Aura healing incorrect amount, fix Defensive Aura healing dead players, Fix Effects being applied to dead players.
> Fix Defensive Aura

- clans/src/main/resources/configs/config.yml
Add more blocks to the non-restorables
> Update nonRestorableBlock list

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
Remove the bed when a clan is being disbanded
Fixes #819
> Remove bed on disband

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Blink.java
- champions/src/main/resources/configs/skills/skills.yml
- Sets de-blink duration to 4 (Down from 6)
> deblink nerf

- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/commands/BalanceCommand.java
Fix paying money to offline players instead going to an online player
Change client search to use offline (was advancedOnline)
Add get to balance commands.
> Fix paying money to offline players

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Bloodshed.java
Fix chat level for speed strength being 1 higher
/tp
> Fix Bloodshed chat level

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Stampede.java
- champions/src/main/resources/configs/skills/skills.yml
- Increases max speed to 3 (up from 2)
- Increases time between charges to 7 (up from 4)
> revert stampede speed

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Cleave.java
- champions/src/main/resources/configs/skills/skills.yml
- Now has a maximum of 3 blocks reach from the target enemy regardless of level
> Cleave Nerf

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Recall.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Slash.java
- champions/src/main/resources/configs/skills/skills.yml
Recall and SmokeBomb rescalling
Change both to level 3 skills with proper values
Slash yellow numbers changed back to static values
> Passive A Assassin, Slash fix

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/FreezeCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/KillCommand.java
> Fix Freeze Especially for Busjack (disable /kill while frozen)

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Concussion.java
- champions/src/main/resources/configs/skills/skills.yml
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/EffectTypes.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/types/negative/ConcussedEffect.java
Concussion is one of the worst abilities in the game because it doesn't provide anything new. I have reworked it into a skill that **reduces the hit speed** of your target opposed to simply **blinding** them. Now, with a **12.0 second** base cooldown, this skill can be used often and will give birth to **fresh interactions.** As abilities like **Combo Attack**, **Null Blade**, and **Wolf's Fury** that are directly dependent on melee attacks can now be fought against in a unique manner.
> Concussion Rework

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/delayedactions/DelayedActionListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/data/PriorityData.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/data/PriorityDataBlockingQueue.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/data/PriorityPairComparator.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/display/TitleQueue.java
Fix Title flickering on c home. 
Now flickers if cancels (needs fixing)
Move Delayed Action to title queue
Fixes #861
> Fix Title Flickering

- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/display/ActionBar.java
Change ActionBar to use PriorityDataBlockingQueue
Fixes possible not safe thread behavior, explicitly orders components of equal priority by most recent.
> Change ActionBar to PriorityDataBlockingQueue

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/FastRecovery.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/ArcticArmour.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Void.java
- champions/src/main/resources/configs/skills/skills.yml
CHANGE MAX LEVEL TO 3
ARCTIC ARMOR: 4/5/6 BLOCK RADIUS, 26/22/18 MANA USAGE
VOID: 2/2.5/3.0 DAMAGE REDUCTION, 28/26/24 MANA USAGE
IMMOLATE -> 28/24/20 MANA USAGE
Include that Fast Recovery is changed to values: 15/25/35
> Mage Passive A Changes, Fast Recovery

- champions/src/main/java/me/mykindos/betterpvp/champions/stats/impl/ChampionsCombatLeaderboard.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/leaderboard/ClanLeaderboard.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/stats/impl/GlobalCombatLeaderboard.java
- core/src/main/java/me/mykindos/betterpvp/core/menu/impl/ViewDescribableMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/Leaderboard.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/LeaderboardCategory.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/command/LeaderboardCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/menu/LeaderboardCategoryMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/menu/LeaderboardListMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/menu/LeaderboardMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/stats/repository/LeaderboardManager.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/leaderboards/BiggestFishLeaderboard.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/leaderboards/FishingCountLeaderboard.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/leaderboards/FishingWeightLeaderboard.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/mining/leaderboards/MiningOresMinedLeaderboard.java
Add parent menus for leaderboards
> Leaderboard galore

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
> Territory popup - changed title to subtitle

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/ThreateningShout.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/data/ThreateningShoutData.java
- champions/src/main/resources/configs/skills/skills.yml
-Now shoots a projectile forward that gives vulnerability to anyone it hits.
-After 0.6 seconds, the projectile will explode along the line, dealing damage to those nearby
-This results in a more skill-shot-oriented way of applying vulnerability and gives extra functionality for enemies that stay In the line of fire for too long.
https://github.com/Mykindos/BetterPvP/assets/145294235/c2c1a9bf-d1a8-4590-a34d-683752a5d253
> Threatening Shout Rework

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/UnclaimSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/utilities/UtilClans.java
Added logic to prevent people from splitting their claims up.
#814
> Added logic to prevent people from splitting their claims up.

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/UnclaimSubCommand.java
Allow administrating clients to unclaim territory from all clans
Fixes #902
> Allow players in Client Admin to unclaim any territory

- core/src/main/java/me/mykindos/betterpvp/core/menu/Windowed.java
> #850 - Add logs for whenever a player opens an inventory

- clans/src/main/java/me/mykindos/betterpvp/clans/progression/perks/ForestFlourisher.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/builds/menu/WoodcuttingProfessionMenu.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/ForestFlourisherSkill.java
- progression/src/main/resources/configs/config.yml
- progression/src/main/resources/configs/professions/woodcutting.yml
- This perks makes any saplings the player plants grow significantly faster
- At level 1, the player's saplings take **90** seconds to grow and this time decreases by **2** seconds per level
- Maxed out, a player can grow a tree in **30** seconds
> Woodcutting Perk: Forest Flourisher

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/EnergyShopSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanEnergyTip.java
- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/DailyTip.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/DailyCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/cooldowns/CooldownManager.java
reword clan energy tip to be correct, add a way to open the energy menu from tip. Fix daily tip showing when you had already used it. Updated javadocs for cooldown manager functions to indicate what the returned boolean meant
Fixes #910
> Fix Clan Energy Tip, Daily tip

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/TreeFellerSkill.java
- Fixed the really ambiguous cooldown message
- Made it so **Tree Feller** will work (horizontally) on the initial block that is chopped
> Woodcutting - Tree Feller Improvements

- core/src/main/java/me/mykindos/betterpvp/core/combat/click/RightClickListener.java
> Improve right-click threshold

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/builds/menu/WoodcuttingProfessionMenu.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/BarkBounty.java
- progression/src/main/resources/configs/professions/woodcutting.yml
- progression/src/main/resources/progression-migrations/V2__Create_items.sql
- This perk gives stripping logs a purpose; when you strip a log, while possessing this perk, there is a chance that you will get an item called **Tree Bark**
- **Tree Bark** will have some value in the shops (eventually but not in this pr)
- this perk/skill has 250 levels
https://github.com/Mykindos/BetterPvP/assets/135760919/aded4775-f4e0-4b70-a020-bebb55868268
> Woodcutting Perk: Bark Bounty

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- I had an error in the bark bounty pr. this fixes that
> Fixed problem where if clickedBlock was null, skill wouldn't activate

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/ShowItemCommand.java
Add a command that allows players to share what item they are holding
Fixes #929
> #929 - Add /showitems

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/Overcharge.java
- champions/src/main/resources/configs/skills/skills.yml
Added a charge bar logic for overcharge instead of the old logic
base charge values and increments need to be balanced lol
#408
> Fixed #408 - Overcharge Bar

- core/src/main/java/me/mykindos/betterpvp/core/components/shops/ShopCurrency.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilInventory.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/ForestFlourisher.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/PropaguleListener.java
- progression/src/main/resources/configs/config.yml
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/listeners/ShopListener.java
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/menus/buttons/ShopItemButton.java
- shops/src/main/resources/shops-migrations/V2__Create_default_shopitems.sql
- Turned Fisherman -> Tradesman so that it can include all professions
- Woodcutting items added are **Power Axes, Booster Axes, and Standard Axes** which can all be bought with **Tree Bark** at shops
- Added **Mangrove Propagules (saplings)** which can exclusively be bought from the shops with **Tree Bark**
- - This type of tree yields *more* xp that the other standard types
- - Their saplings **cannot** be obtained through leaf decay, bone mealing mangrove leaves, or through generation
> Added Woodcutting to Shops with Mangrove Trees

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/Rune.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/alacrity/AlacrityBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/conquering/ConqueringBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/fortune/FortuneBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/frost/FrostBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/haste/HasteBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/insight/InsightBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/listeners/FortuneRuneListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/listeners/RuneCraftingListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/power/PowerBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/reinforced/ReinforcingBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/resistance/ResistanceBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/scorching/ScorchingBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/unbreaking/UnbreakingBase.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/WoodcuttingHandler.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/event/PlayerChopLogEvent.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/WoodcuttingListener.java
- Added **Fortune Rune** compatibility with axes
- Logs chopped have a some ______% chance of dropping "double" logs (pretty much just an additional log)
> Fortune Rune for Axes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/SoulBonds.java
- champions/src/main/resources/configs/skills/skills.yml
Changed name to SoulBonds
Moved to Warlock
Made 3 level skill
Tweaked Values
Changed particles and sound effects accordingly
> LifeBonds Changes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/HoldPosition.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/HiltSmash.java
Added an additional sound to indicate failing Hilt smash, so people do not get confused
> Hilt Smash Fail indicator

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
> fixed clone issues

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
> Fix flash/blink/evade/slash

- clans/src/main/java/me/mykindos/betterpvp/clans/commands/commands/ClansCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/CannonWeapon.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/event/CannonPlaceEvent.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/listener/ClansCannonListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/model/Cannon.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/cannon/model/CannonManager.java
> Allow unbound cannons that can be used by anyone

- core/src/main/java/me/mykindos/betterpvp/core/inventory/inventoryaccess/impl/AnvilInventoryImpl.java
> Fix AnvilInventoryImpl

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
Stop the flash logic chain if it would violate going out of the world border.
Fixes #795
> Fix flashing through the world border

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
- champions/src/main/resources/configs/skills/skills.yml
- Fixed vengeance doing way more damage than intended, brought it in line with what mineplex was
> Vengeance Fix

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClaimSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/utilities/ClansNamespacedKeys.java
Add a cooldown on claiming territory recently unclaimed due to a Clan disband.
Fixes #833
> Add cooldown on claiming disbanded territory

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/ForestFlourisher.java
- Changed **Forest Flourisher's** cycle from growing saplings every `5 seconds` -> `60 seconds`
- I've done the research and I'm fairly sure that this is how often growth works in the game.
> Woodcutting: Fix Forest Flourisher Cycle

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/core/ClanCore.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/transport/ClanTravelHubMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/transport/CoreTransportButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/transport/ShopTransportButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/transport/SpawnTransportButton.java
Fix transport feedback for spawn/shops. Change to Clan Core instead of Clan home
Fixes #998
> Fix transport feedback

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Fortify.java
> Fix Fortify not using config for damage reduction, add particles

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Bloodshed.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Cleanse.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/TormentedSoil.java
- champions/src/main/resources/configs/skills/skills.yml
> warlock health stuff

- shops/src/main/resources/shops-migrations/V2__Create_default_shopitems.sql
Fixed issue w/ wrong item name in shops
#1047
> Fixed #1047

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Cleave.java
> fix particles on cleave playing on every hit

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/Resistance.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/FireBlast.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Immolate.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Inferno.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/IncendiaryShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/listeners/RuneItemListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java
Make resistance reduce duration of fire,
Change all instances of set fire ticks to use UtilEntity.setFire, which sets fire and gives damage credit
Fixes #1044
Fixes #1024
> Make Resistance reduce Fire, make player applied Fire give damage/kill credit

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/builds/menu/MiningProfessionMenu.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/mining/MiningProgressionSkill.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/mining/Smelter.java
- progression/src/main/resources/configs/professions/mining.yml
Added the smelter perk. Increases the chance of ores/stone auto smelting when mined
tested with fields
tested in other territories
#110
> Added Smelter perk to Mining tree

- core/src/main/java/me/mykindos/betterpvp/core/combat/listeners/CombatListener.java
> #1078 - Disable knockback if it is fire damage attributed to a player

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/ArcticArmour.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/HolyLight.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/MagmaBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/NullBlade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Void.java
- champions/src/main/resources/configs/skills/skills.yml
- Arctic armor slowness is only applied when the user hits players
- Glacial blade no longer uses energy
- Magma blade now extinguishes on hit to prevent it being broken
- Void energy lost when being hit reduced from 3.0 to 2.5
> Mage Passive Changes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/WhirlwindSword.java
- champions/src/main/resources/configs/skills/skills.yml
Whirlwind distance change to 5 fixed
Scale FleshHook cooldown to match mineplex - changed it to 14 (-1) instead of 18 (-2)
- [+] I have performed a self-review of my code
- [+] I have tested my changes.
> Brute changes - Sword Abilities

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/resources/configs/config.yml
- Made dominance gained per kill a fixed 5.0% (20 kills for 100%)
> Dominance Scaling

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
was the wrong particle before, probably 1.21 stuff
> fix smoke bomb particle

- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
- core/src/main/java/me/mykindos/betterpvp/core/light/BPvPLight.java
- core/src/main/java/me/mykindos/betterpvp/core/light/LightManager.java
- core/src/main/java/me/mykindos/betterpvp/core/light/listener/LightListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilLocation.java
Add light manager, for use in cosmetics
> Add Light Manager

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ComboAttack.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SilencingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ViperStrikes.java
> Fix #1037 - prevent assassin passives activating on cancelled damage events

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/core/mailbox/ClanMailboxButton.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/core/menu/CoreMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/menus/buttons/ClanMemberButton.java
Add a notifyWindows to clan member button
Add previous menu for vault/mailbox
Fixes #1064
Fixes #1057
> Clan related GUI fixes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansDeathListener.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLogListener.java
Fix combat logging not giving dominance when clicking the sheep
Fix combat log logic being incorrect
Fixes #1089
> Fix combat logging not giving dominance

- core/src/main/java/me/mykindos/betterpvp/core/framework/customtypes/KeyValue.java
- core/src/main/java/me/mykindos/betterpvp/core/loot/LootChest.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/WeighedList.java
- core/src/test/java/me/mykindos/betterpvp/core/utilities/model/WeighedListTest.java
Add infrastructure to more easily access loot tables and their chances.
> Add configs for dungeons/events

- core/src/main/java/me/mykindos/betterpvp/core/framework/adapter/Compatibility.java
> Mineplex store integration

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
> Check max damage before setting max damage

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/coins/CoinDeathListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/coins/CoinItem.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/coins/CoinPickupListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEnergyListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/utilities/ClansNamespacedKeys.java
- clans/src/main/resources/configs/config.yml
- Default config values set to enabled, and 10% of coins dropped
#1100
> Players drop coins on death

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
- core/src/main/java/me/mykindos/betterpvp/core/world/CoreWorldListener.java
> Let players /kill instantly while in safezones and while in own claim

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
- champions/src/main/resources/configs/skills/skills.yml
- Fixed storm sphere wrong prepare sound
- Fixed incorrect description
- Now Plays a sound when it bursts
- Fixed storm sphere lightning setting entities on fire(lol)
- Prevent storm sphere from silencing players through walls(lol)
- Decreased radius by 1
> Fix Storm Sphere

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
fix small iterator bug in storm sphere
> Storm sphere bug fix

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/TreeCompactor.java
- progression/src/main/resources/progression-migrations/V3_1__Fix_compacted_log_modeldata.sql
- progression/src/main/resources/progression-migrations/V3__Create_compacted_log_item.sql
- shops/src/main/resources/shops-migrations/V4__Add_compacted_log.sql
- shops/src/main/resources/shops-migrations/V6__fix_compacted_log_modeldata.sql
- Let me know if I need to make *another* migration instead of changing the current ones
- Also, the reason for changing the wood type is because if you *just* change the model data on the Oak Wood from `0` -> `1` in the migrations, it doesn't fix the issue. So this fix should be a guaranteed fix
#1123
> Swapped OAK_WOOD for CRIMSON_HYPHAE

- champions/src/main/resources/configs/config.yml
- clans/src/main/resources/configs/config.yml
- core/src/main/resources/configs/config.yml
See also https://github.com/Mykindos/BetterPvP-Private/pull/37
> Update Default Configs

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/mining/Smelter.java
smelter only works with diamond+
> smelter only works with diamond+

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/transport/ClanTravelHubMenu.java
> #1154 - Re-arrange transport menu to match world layout

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/Fissure.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/axe/WindBurst.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/BarbedArrows.java
Fixes #1153 
Fixes #1126 
Fixes #1050
> Minor description changes

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/ClaimSubCommand.java
Fixes being able to corner claim through /c claim
> Fix corner claiming

- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/Punishment.java
- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/commands/PunishmentAddCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/commands/PunishmentHistoryCommand.java
History:
Show username of punisher instead of UUID
Show remaining duration of punishment
Force a reason on all punishments
Fixes #839
Fixes #840
> Punishment Improvements

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/AllySubCommand.java
Clear up alliance feedback messages
Fix alliance logic to work on direct alliances only
Fixes #1156
> Improve Alliance feedback, fix ally bug

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
> Prevent water buckets from being placed

- clans/src/main/java/me/mykindos/betterpvp/clans/fields/FieldsListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
Update damaging items to use ItemStack#damage instead of trying to use custom logic to do so.
Make pickaxes take durability damage in fields
Fixes #1120
> Update Item Durability

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
> Prevent attempting to damage/break air

- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLog.java
Share who clicked the combat log sheep
Fixes #1165
> Show who clicked the combat log sheep

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/Takedown.java
> Prevent takedown from colliding with armor stands

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
- clans/src/main/resources/clans-migrations/V2_1__Lapis_lore.sql
Make it a BPvPItem
Fixes #1210
> Add lore to lapis block that explains how it is used

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/data/ShockingStrikesData.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/ShockingStrikes.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SilencingStrikes.java
- champions/src/main/resources/configs/skills/skills.yml
Increased timeSpan to 1.0 for silencing strikes
Made shocking use the same logic as silencing strikes
Shocking now shocks every hit but slows every 3rd hit
increased silence time and scaling
changed slowness duration of shocking to be the same as silencing
> Silencing Strikes and Shocking Strikes changes

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Stampede.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Pestilence.java
> Fix #1221 and #1220

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansCombatListener.java
To combat WP evasion
Fixes #1209
> Prevent players from leaving a clan while in combat

- core/src/main/java/me/mykindos/betterpvp/core/chat/ChatListener.java
- core/src/main/java/me/mykindos/betterpvp/core/chat/commands/SilenceChatCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/client/Client.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientSQLLayer.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/IgnoreCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/MessageCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/ReplyCommand.java
- core/src/main/resources/configs/config.yml
- core/src/main/resources/core-migrations/global/V7__Add_ignore.sql
Add an ignore system, currently works on messages only.
Prevent muted players from messaging other players
> Add ignore for messages, add a way to silence global chat

- core/src/main/java/me/mykindos/betterpvp/core/framework/delayedactions/DelayedActionListener.java
> Teleporting now cancels delayed actions

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/AutoPlanter.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/EnchantedLumberfall.java
> Fixed woodcutting dependencies

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/RootingAxe.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Pestilence.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/TetherShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/protection/ClansProtectionListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/FieldsListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/block/LootChest.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/FieldsInteractable.java
- clans/src/main/java/me/mykindos/betterpvp/clans/fields/model/FieldsOre.java
- clans/src/main/java/me/mykindos/betterpvp/clans/progression/listener/ClansFishingListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/effects/ProtectionListener.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/delayedactions/DelayedActionListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/fish/Fish.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/listener/FishingListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/loot/TreasureType.java
Fix various issues with protection
Fixes #1187
Fixes #1184 
Fixes #1183 
Fixes #1174 
Fixes #1139 
Fixes #1129
> Protection Fixes

- shops/src/main/resources/shops-migrations/V12__Fix_custom_model_data_building.sql
> ix Building Shopkeeper having custom model data for some items

- champions/src/main/java/me/mykindos/betterpvp/champions/tips/tips/weapons/CrossbowWeaponTip.java
> FIx CrossbowWeaponTip being empty

- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/Gamer.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/death/DeathListener.java
> Give temporary immunity from being combat tagged after death

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/Rune.java
- core/src/main/java/me/mykindos/betterpvp/core/framework/CoreNamespaceKeys.java
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/listeners/ShopListener.java
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/utilities/ShopsNamespacedKeys.java
Pull up no shop sell namespacedkey to core, apply no shop sell to runed items
Fixes #1181
> Prevent imbued items from being sold

- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/Punishment.java
> Use completeable futures to fetch punisher name

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/SingleStatRune.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/frost/FrostBase.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/runes/scorching/ScorchingBase.java
Does not fix the underlying issue though
#1241
> Prevent runes from being stacked

- core/src/main/java/me/mykindos/betterpvp/core/client/gamer/commands/SetProtectionCommand.java
Change setprotection to check for online in a different way, to improve how it works
Fixes #1267
> Change how setprotection gets player

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Deflection.java
- champions/src/main/resources/configs/skills/skills.yml
> Fix deflection base charges

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/TreeCompactor.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/commands/TreeCompactorCommand.java
> Cherry logs now work w/ treecompactor

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/commands/TreeCompactorCommand.java
> Fix /treecompactor crashing the server if used in creative

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
> Prevent loading a lootable with a disabled item

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
Pulled redstone block logic to utilblock
Fixes #1292
> Fix ice prison replacing some redstone items

- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/effects/ProtectionListener.java
> Remove block break warning, make reserve time configurable

- core/src/main/java/me/mykindos/betterpvp/core/effects/types/negative/BleedEffect.java
Clarify that bleed damage is true damage
Fixes #1188
> Make bleed damage clarify that it is true damage

- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanWaterBlockTip.java
>  Add water block tip

- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/RestoreBlockListener.java
> Prevent damaging self with restore blocks

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/ArcticArmour.java
> Fix Artic Armor giving slowness on non-melee hits

- clans/src/main/java/me/mykindos/betterpvp/clans/world/SpongeListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
> Add fall damage immunity when using sponges

- clans/src/main/resources/configs/vault-restrictions.yml
vault-restrictions.yml had a special case for the hyper axe, this has been fixed for the live server
> #1324 - Update vault-restrictions.yml to not include an extra hyper-axe

- core/src/main/java/me/mykindos/betterpvp/core/command/Command.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/AdminVanishCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/EffectListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/effects/VanishListener.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/types/positive/VanishEffect.java
Explicity remove players from tab list for commandVanish, add fake join/leave messages for commandVanish, show commandVanished players to staff. Run vanish logic for players that join the server.
Run onReceive for players that join the server with active effects
Fixes #1333
> Improve Vanish

- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientManager.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientRedisLayer.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientSQLLayer.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/model/manager/PlayerManager.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/search/SearchEngineBase.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/search/SearchEngineHuman.java
Use `@Nullable` annotations and handle possible errors with having a nullable parameter.
> Explicitly handle null names and UUIDs in offline/advanced search

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/ThreateningShout.java
- champions/src/main/resources/configs/skills/skills.yml
- Change radius to 1.5 from 3
- Change Vulnerability level to 1 from 2
- [+] I have performed a self-review of my code
- [+] I have tested my changes.
> Threating Shout Nerf

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Bloodlust.java
> Fix bloodlust not using the correct levels for effects

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Frailty.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Impotence.java
- side note, i didn't realize how good frailty probably is against bosses.
- Warlock is a PvE demon
> Small feedback particles for Impotence and Frailty

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/SoulHarvest.java
- audio broken in demo
https://github.com/user-attachments/assets/87c23e17-3be1-4d10-ac40-fce56b915819
> Added sound and subtle particle to soul harvest

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/Clan.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/core/ClanCore.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
> Give dominance info on disband

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/passives/Siphon.java
- champions/src/main/resources/configs/skills/skills.yml
- Before, Siphon was an inconsistent ability and was pure RNG.
- Now, it still has an RNG aspect (gaining health) but the Speed component of the ability is more consistent
- Made great improvements to the logic of the ability
- The ability still does the same stuff, just now it does it consistently
> Significant Improvements to Siphon

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
> Prevent Stripping logs in combat

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/WoodcuttingHandler.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/SaplingGrowListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/listener/StrippedLogListener.java
> Fixed bug where saplings still had player placed data

- core/src/main/resources/configs/config.yml
- shops/src/main/resources/shops-migrations/V15_4__Add_saplings.sql
- shops/src/main/resources/shops-migrations/V15_5__Add_prismarine.sql
- shops/src/main/resources/shops-migrations/V17__Fix_lever.sql
Add saplings to lumberjack, primsarine to resources
#1370
> Add prismarine and saplings to shops

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
Take location by block not player
> Fix leather and netherite mining issues

- core/src/main/resources/configs/config.yml
> Update default config

- core/src/main/resources/configs/rules.yml
> fix rule typo

- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/doors/IronDoor.java
- clans/src/main/java/me/mykindos/betterpvp/clans/weapons/impl/doors/IronTrapdoor.java
> Add spruce to iron_door and iron_trapdoor

- core/src/main/resources/configs/rules.yml
> Add Grief rule

- core/src/main/java/me/mykindos/betterpvp/core/items/listener/ItemListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/loot/TreasureType.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/mining/listener/MiningListener.java
> Fix fishing and mining items not stacking

- clans/src/main/java/me/mykindos/betterpvp/clans/logging/menu/ClanKillLogMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/logging/menu/ClansOfPlayerMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/logging/menu/PlayersOfClanMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/items/LootSpawnItemLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/menu/CachedLogMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/menu/button/LocationButton.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilWorld.java
> Fix UI log errors, improve error communcation

- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLog.java
Uses same logic as offline invsee 
Fixes #1427
> Change how combat sheep gets items to drop and save.

- core/src/main/java/me/mykindos/betterpvp/core/items/ItemHandler.java
- core/src/main/java/me/mykindos/betterpvp/core/items/listener/ItemListener.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/fishing/FeelingLucky.java
Fixes only smelting 1 item at a time (change where item update happens)
Now update items on every click
Now remove custommodel 0 from items
Do not assign custom model 0 to doubled items
Fixes #1432
> Fix items not stacking or smelting...again

- core/src/main/java/me/mykindos/betterpvp/core/world/CoreWorldListener.java
> Fixed mangrove bug where some saplings wouldn't grow

- clans/src/main/java/me/mykindos/betterpvp/clans/logging/menu/ClanKillLogMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/logging/menu/ClansOfPlayerMenu.java
- clans/src/main/java/me/mykindos/betterpvp/clans/logging/menu/PlayersOfClanMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/clans/ClanSetHomeLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/menu/CachedLogMenu.java
> Change how logs log errors to log better

- clans/src/main/java/me/mykindos/betterpvp/clans/world/WorldListener.java
> Prevent inventories from picking up blood

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/world/WorldListener.java
> Prevent players pushing minecarts, minecarts moving off of rails

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/pillage/PillageListener.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/clans/ClanPillageLogFormatter.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/menu/button/StringFilterButton.java
- core/src/main/java/me/mykindos/betterpvp/core/logging/repository/LogRepository.java
fix pillage log not having an action
> Fix logs fetching logs with no action

- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/rules/Rule.java
- core/src/main/resources/configs/rules.yml
> Fix build lock and pvp lock punishment types not working correctly for rules

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/LevelField.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
- champions/src/main/resources/configs/skills/skills.yml
Improved config for both level field and vengeance. Update level field description to be clearer
Fixes #920 
Fixes #765
> Update level field description and config, update vengeance config

- core/src/main/resources/configs/rules.yml
> Add filter bypass rule

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/ClanManager.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/repository/ClanRepository.java
- clans/src/main/java/me/mykindos/betterpvp/clans/logging/KillClanLog.java
Explicitly handle a null clan when getting clan by id
> Fix NPE/IllegalArguementException with ClanKillLogs

- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLog.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLogListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilPlayer.java
> Reset player location to spawn after their combat log sheep is clicked

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/passives/Bloodlust.java
> Make Bloodlust not work on animals (chickens, axolotols, pigs, etc)

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/data/PestilenceProjectile.java
> Fix pestilence working on allies

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/global/LevelField.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/BullsCharge.java
> Move level field to global, prevent knockback from skills in bulls charge

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/TriShot.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/HuntersThrill.java
🐐
#trii shot bug issue somewhere idk couldnt find
> Fixed tri shot damage and made it compatible with hunter's thrill

- shops/src/main/java/me/mykindos/betterpvp/shops/shops/menus/ShopMenu.java
> Remove warning for index out of bounds in shopmenu (incorrect)

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/pillage/PillageListener.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/OfflineMessage.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/OfflineMessagesHandler.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/OfflineMessagesListener.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/OfflineMessagesRepository.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/commands/AdminOfflineMessagesCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/commands/OfflineMessagesCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/client/offlinemessages/menu/OfflineMessagesMenu.java
- core/src/main/java/me/mykindos/betterpvp/core/client/properties/ClientProperty.java
- core/src/main/java/me/mykindos/betterpvp/core/client/punishments/PunishmentHandler.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientListener.java
- core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientSQLLayer.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLog.java
- core/src/main/java/me/mykindos/betterpvp/core/combat/combatlog/CombatLogListener.java
- core/src/main/resources/core-migrations/global/V15__Add_offline_messages.sql
Add OfflineMessages, messages that are sent to players, that …on the next login, they will receive.
OfflineMessages are sent for the following:
Your clan is disbanded
Your clan is pillaged
You are kicked from a clan
Your combat log sheep was clicked
You were punished
Fixes #1341 
Fixes #1277
> Add OfflineMessages

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/listeners/SkillListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/WindBlade.java
Change instances that check for liquid to clarify that it is liquid, not just water.
Fixes #1347
> Clarify water feedback that is actually liquid

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansCombatListener.java
> Prevent joining a clan while in combat

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/transport/ClanTravelHubMenu.java
> Update transport menu to match world

- clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanDoorTip.java
> Add a tip for iron doors

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/HuntersThrill.java
> Add speed duration to hunter's thrill description

- progression/src/main/java/me/mykindos/betterpvp/progression/profession/fishing/commands/FishingExperienceCommand.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/mining/commands/MiningExperienceCommand.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/commands/WoodcuttingExperienceCommand.java
Correctly save profession experience from admin commands
Fixes #1487
> Fix admin experience commands not saving correctly

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/general/ListCommand.java
> Add rank colors to /list

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilInventory.java
Fix incorrect logic with removing from hand
> Fix /treecompactor giving extra compacted logs in some instances

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/commands/subcommands/BankSubCommand.java
- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanBankListener.java
Drop clan bank on core destroy
Fixes #1278
> Remove bank withdrawl restrictions

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/BuildManager.java
correctly handle level 1 skills
> Fix Random Build Button causing StackOverflow

- core/src/main/java/me/mykindos/betterpvp/core/command/commands/qol/CenterSelfCommand.java
> Add center self command to help map defining

- core/src/main/java/me/mykindos/betterpvp/core/menu/Menu.java
> Fix Menu.getFixedLore compile issue

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/Takedown.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/data/BlockTossObject.java
> Add sounds to block toss and takedown

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/listeners/BuildListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/ClassSelectionMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/ClassSelectionButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/ToggleShowPassiveButton.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/BuildCommand.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/commands/admin/PromptBuildCommand.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/RoleEffect.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/RoleManager.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/RolePassive.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/passives/AssassinPassiveListener.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/roleeffects/AssassinListener.java
- champions/src/main/resources/configs/config.yml
- Added a toggle feature to the class selection menu so players have the option to see role passives
- mykindos please add more role passives
https://github.com/user-attachments/assets/0afebc44-9db4-4363-a578-45a8c2b6acfb
> Updated Class Selection Menu to Feature Role Passives

- core/src/main/java/me/mykindos/betterpvp/core/world/blocks/RestoreBlockListener.java
prevent ice prison, rupture etc. from breaking item frames (and other hanging items)
Fixes #1477
> Prevent restoreblock's from breaking hanging items

- clans/src/main/java/me/mykindos/betterpvp/clans/progression/perks/TreeFeller.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/TreeFellerSkill.java
- progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/WoodcuttingHandler.java
Manually drop the logs dropped from treefeller and reserve them if the player has protection
Fixes #1421
> Fix treefeller not working with protection

- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/state/EndingStateHandler.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/model/team/Team.java
- game/src/main/java/me/mykindos/betterpvp/game/guice/platform/MineplexPlatformProvider.java
- game/src/main/java/me/mykindos/betterpvp/game/mineplex/listener/MineplexExperienceListener.java
As per the Mineplex team, add support for Mineplex's leveling system. For now, only a wait of 75 is given to winners and 25 to all other participants. No other game context is taken into consideration, yet.
> Experience support

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/roleeffects/AssassinListener.java
> Fix giving assassin speed to non-assassins

- game/src/main/java/me/mykindos/betterpvp/game/framework/model/world/MappedWorld.java
Fix lobbies staying in mapped world while in Waiting State and causing dead lobbies
> Fix lobbies going into waiting state and breaking

- game/src/main/java/me/mykindos/betterpvp/game/impl/domination/Domination.java
> Balance: Increase capture point score from 4 -> 8

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/listener/FlagHolderListener.java
Fixes #1572
- [x I have tested my changes.
> Drop the flag when a player quits

- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/team/TeamBalancerListener.java
> Set players not chosen for a team to spectator

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagPlayerHandler.java
> Correctly cancel Smoke Bomb on flag pickup

- core/src/main/java/me/mykindos/betterpvp/core/command/listener/CommandListener.java
> Allow certain Mineplex commands

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/SmokeBomb.java
> Prevent smoke bomb reappear message from sending twice

- core/src/main/java/me/mykindos/betterpvp/core/command/listener/CommandListener.java
> Add report and ignore to mineplex allowed commands

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/CaptureTheFlag.java
- game/src/main/java/me/mykindos/betterpvp/game/impl/domination/Domination.java
> Game description now pulls from attributes for values

- core/src/main/java/me/mykindos/betterpvp/core/world/SalvagerListener.java
> Fix Salvager not updating names of materials

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilPlayer.java
> Remove Players in Creative or Spectator from getNearbyEntities

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java
> Fix kick grammar error

- game/src/main/java/me/mykindos/betterpvp/game/framework/model/team/TeamSpawnPointProvider.java
Choose spawns sequentially, to reduce the chances players spawn in the same place as another player.
Fixes #1612
> Choose spawns sequentially for team games

- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/player/PlayerInventoryListener.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/manager/InventoryProvider.java
> Keep armor while spectating to allow skills and energy to recharge

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/RoleListener.java
> Leave soundprovider as default for fall damage

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java
> Make flash charge quicker in spectator

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/BuildMenu.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/builds/menus/buttons/DeleteBuildButton.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/player/PlayerControllerListener.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/player/PlayerInventoryListener.java
- game/src/main/java/me/mykindos/betterpvp/game/framework/model/setting/hotbar/HotBarLayoutManager.java
Delete hotbar layout on delete build, show previous menu from delete build instead of creating a new one. Remove unused parameters from delete build. Update inventory after deleting a build
Fixes #1624
> Fix Delete Build Button not acting as expected

- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilItem.java
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/listeners/ShopListener.java
- shops/src/main/java/me/mykindos/betterpvp/shops/shops/menus/buttons/ShopItemButton.java
Drop any remaining items from inventory add on the ground, as a failsafe.
Fixes #1610
> Prevent buying stacks of items with an itemstack max size of 1. 

- game/src/main/java/me/mykindos/betterpvp/game/framework/listener/team/TeamBalancerListener.java
> Randomize unassigned players before assigning teams

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagPlayerHandler.java
> Silence flag holders

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/core/ClanCore.java
> Fix Clan#toString causing stack overflow error due to circular reference in ClanCore#toString

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/roles/listeners/roleeffects/AssassinListener.java
- core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/AdminVanishCommand.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/Effect.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/EffectManager.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/VanillaEffectType.java
Change Effect and EffectManager to allow the option of not showing particles.
Must also merge https://github.com/Mykindos/BetterPvP-Private/pull/55
> Remove Particles from Assassin speed

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/axe/UnstoppableForce.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
> Let unstoppable force go up slabs

- game/src/main/java/me/mykindos/betterpvp/game/impl/domination/model/CapturePoint.java
Remove players from capturing if not connected
Fixes #1638
> Fix disconnected players blocking/capturing points

- core/src/main/java/me/mykindos/betterpvp/core/logging/formatters/clans/ClanUnclaimChunkLogFormatter.java
> Fix unclaim title

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/GlacialBlade.java
> Add hit sound to glacial blade

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/data/AxeProjectile.java
> Magnetic axe no longer collides with entities it cannot hurt

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/data/BlockTossObject.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/BlockToss.java
> Despawn BlockTossObjects during invalidate player

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Evade.java
- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/sword/Riposte.java
> Fix evade proccing when player does not have the skill

- champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/GiantsBroadsword.java
- core/src/main/java/me/mykindos/betterpvp/core/effects/types/positive/RegenerationEffect.java
> Fixed broad

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/CaptureTheFlag.java
> Update CTF description

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/listener/CTFSidebarListener.java
- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagBlock.java
> Show flag dropped and flag taken differently. Show remaining time on flag

- clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansWorldListener.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
> Prevent using pressure plates in a Clan's territory while the clan is offline

- game/src/main/java/me/mykindos/betterpvp/game/impl/ctf/model/FlagPlayerHandler.java
Slowness 1 is very difficult to catch up to normally, increase to slowness 2, but keep the other ways of increasing velocity (i.e. shield smash).
> Increase flag slowness from 1 to 2

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/sword/Inferno.java
- core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilBlock.java
> Fix inferno working in water

- champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/passives/BioticQuiver.java
- champions/src/main/resources/configs/skills/skills.yml
Increases Biotic Quiver Healing to 5/6/7
> Biotic Quiver Buff

- core/src/main/resources/configs/rules.yml
> Add Team Trolling rule

- core/src/main/java/me/mykindos/betterpvp/core/database/connection/MariaDBDatabaseConnection.java
- core/src/main/resources/configs/config.yml
- docker/docker-compose.yml
Change default ports, current default ports are block by windows autmatically now
Fixes #1773
MariaDBDatabaseConnection error now submits.
> #1773 - Change default ports for DB Submit error log for MariaDBDatabaseConnection

- champions/src/main/resources/configs/skills/skills.yml
> Disable Heavy Arrows

- game/src/main/java/me/mykindos/betterpvp/game/command/GameCommand.java
- game/src/main/resources/configs/config.yml
- Game command isnt in config.yml so all the perms default to ADMIN. I'm assuming it's not in the config file for a reason so I put the required rank in the source code for `GameCommand.java`.
> Let mods start champs games
